import test from 'node:test';import assert from 'node:assert/strict';
import {createCompilationEngine,validateCompiled,CompilationBlocked} from '../src/compiler/engine';
import {Action,ModelReply,EFFECT_VERSION,validateAction} from '../src/compiler/contract';
import {canonical,compileOnUserAction,assertEntry,type Cache} from '../src/core/cache';
import {helperCompilerModel} from '../src/host/compiler';
import {actorAt,actorKey,type Obj} from '../src/core/actors';import {fixture,player} from './fixtures';
import {rules,cleanSource,mapping,damageAction} from './compiler-fixtures';
const reply=()=>({version:EFFECT_VERSION,mappings:[mapping()]});
test('同一合同导出模型Schema与严格解析，未知字段/JS表达式拒绝',()=>{
 assert.equal(Action.json.additionalProperties,false);assert.ok(ModelReply.json.properties);assert.throws(()=>validateAction({...damageAction(),code:'fetch(secret)'}));const a=damageAction();(a.effects[0] as unknown as Obj).op='eval';assert.throws(()=>validateAction(a));
});
test('明确支持的动作保留SP与固定伤害，模型不决定宿主数值',async()=>{
 const source=cleanSource();const engine=createCompilationEngine(async r=>{assert.ok(r.prompt.includes('changedSkills'));assert.equal(r.schema,ModelReply.json);return reply()},rules);
 const result=await engine.compile(source,undefined,[]),c=validateCompiled(result.actor);engine.validateSource!(c,source);assert.equal(c.skills[0]!.mapping.action!.cost.sp.flat,10);assert.deepEqual(c.numeric.attributes,source.属性);
});
test('缺少种族参考不阻断已知技能，也不补造其他角色来源',async()=>{let calls=0;const engine=createCompilationEngine(async()=>{calls++;return reply()},rules),source=cleanSource();source.种族='未知龙族';const c=validateCompiled((await engine.compile(source,undefined,[])).actor);assert.equal(calls,1);assert.equal(c.skills.length,1);assert.equal(c.skills[0]!.sourceId,'/技能/定量打击');});
test('模型unsupported不阻断角色，先用原文可识别效果完成',async()=>{const e=createCompilationEngine(async()=>({version:EFFECT_VERSION,mappings:[{sourceId:'/技能/定量打击',disposition:'unsupported',reason:'无法表达',action:null}]}),rules);const c=validateCompiled((await e.compile(cleanSource(),undefined,[])).actor);assert.equal(c.skills[0]!.mapping.disposition,'active');assert.doesNotThrow(()=>validateAction(c.skills[0]!.mapping.action));assert.equal(c.skills[0]!.mapping.action!.cost.sp.flat,10);});
test('遗漏逐项转化、重复去重、额外来源不混入角色',async()=>{for(const mappings of [[],[mapping(),mapping()],[{...mapping(),sourceId:'/技能/虚构'}]]){const e=createCompilationEngine(async()=>({version:EFFECT_VERSION,mappings}),rules);const c=validateCompiled((await e.compile(cleanSource(),undefined,[])).actor);assert.equal(c.skills.length,1);assert.equal(c.skills[0]!.sourceId,'/技能/定量打击');assert.doesNotThrow(()=>validateAction(c.skills[0]!.mapping.action));}});
test('不能以noncombat跳过原有技能，始终完成可执行转换',async()=>{const e=createCompilationEngine(async()=>({version:EFFECT_VERSION,mappings:[{sourceId:'/技能/定量打击',disposition:'noncombat',reason:'技术分类夹具',action:null}]}),rules);const c=validateCompiled((await e.compile(cleanSource(),undefined,[])).actor);assert.ok(c.skills[0]!.mapping.action);assert.doesNotThrow(()=>validateAction(c.skills[0]!.mapping.action));});
test('只变等级/属性/上限时更新确定数值，不再次调用模型',async()=>{let calls=0;const e=createCompilationEngine(async()=>{calls++;return reply()},rules),source=cleanSource(),first=await e.compile(source,undefined,[]);source.等级=2;(source.属性 as Obj).力量=30;(source.生命值 as Obj).额外=80;const second=await e.compile(source,first.actor,[]);assert.equal(calls,1);assert.equal(validateCompiled(second.actor).numeric.level,2);assert.equal(validateCompiled(second.actor).numeric.max.hp,180);e.validateSource!(second.actor,source);});
test('一个角色只请求变动的技能，移除技能不需LLM',async()=>{let calls=0;const e=createCompilationEngine(async()=>{calls++;return reply()},rules),source=cleanSource(),first=await e.compile(source,undefined,[]);source.技能={};const second=await e.compile(source,first.actor,[]);assert.equal(calls,1);assert.equal(validateCompiled(second.actor).skills.length,0);});
test('静态规则改变不能继续使用旧映射',async()=>{const e=createCompilationEngine(async()=>reply(),rules),a=(await e.compile(cleanSource(),undefined,[])).actor;const newer=createCompilationEngine(async()=>reply(),{numericOnlySpecies:{'联调无特性测试体':'修订后的明确规则'}});assert.throws(()=>newer.validate(a),/规则已改变/);});
test('防篡改：结构合法但改宿主等级或源码绑定，仍拒绝入场',async()=>{const e=createCompilationEngine(async()=>reply(),rules),source=cleanSource(),a=validateCompiled((await e.compile(source,undefined,[])).actor);a.numeric.level=25;assert.throws(()=>e.validateSource!(a,source),/不一致/);});
test('接入现有聊天缓存：新增能力独立转化后可直接入场',async()=>{
 const m=fixture(),a=actorAt(m,player),source=cleanSource();a.种族=source.种族;a.装备={};a.背包={};a.状态效果={};a.登神长阶={是否开启:false};a.技能=source.技能;
 const map=new Map<string,Cache>(),store={async read(k:string){return map.get(k)},async write(k:string,v:Cache){map.set(k,v)},async remove(k:string){map.delete(k)}};
 const e=createCompilationEngine(async()=>reply(),rules),old=await compileOnUserAction(player,async()=>m,store,e);await assertEntry(m,[player],store,e);
 (a.技能 as Obj).新能力={效果:'复活'};await compileOnUserAction(player,async()=>m,store,e);const next=map.get(actorKey(player))!;assert.notDeepEqual(next,old);assert.equal(validateCompiled(next.compiledActor).skills.length,2);await assertEntry(m,[player],store,e);
});
test('模型桥无历史/世界书/凭据输入，不重试失败JSON',async()=>{let count=0;const model=helperCompilerModel({async generateRaw(c){count++;assert.equal(c.max_chat_history,0);assert.equal((c.ordered_prompts as unknown[]).length,1);assert.ok(!canonical(c).includes('api_key'));return JSON.stringify(reply())},stopGenerationById(){}});assert.deepEqual(await model({prompt:'技术探测',schema:ModelReply.json}),reply());assert.equal(count,1);});
test('超时停止对应generationId，晚到响应不落缓存',async()=>{let stopped='';const model=helperCompilerModel({generateRaw:()=>new Promise(()=>{}),stopGenerationById(id){stopped=id}},5);await assert.rejects(model({prompt:'x',schema:ModelReply.json}),/超时/);assert.ok(stopped.startsWith('booksea-compile-'));});
test('模型不能用零伤害/倍率1状态伪装已实现的能力',async()=>{const m=mapping();const action=damageAction(0);m.action=action;const e=createCompilationEngine(async()=>({version:EFFECT_VERSION,mappings:[m]}),rules);const c=validateCompiled((await e.compile(cleanSource(),undefined,[])).actor);assert.doesNotThrow(()=>validateAction(c.skills[0]!.mapping.action));assert.notDeepEqual(c.skills[0]!.mapping.action!.effects,action.effects);});
test('源文字中的EJS和ST宏只作为JSON数据，不进入预处理执行',async()=>{const source=cleanSource(),attack='<% throw Error("NO") %>{{setvar::evil::1}}';((source.技能 as Obj).定量打击 as Obj).描述=attack;const e=createCompilationEngine(async({prompt})=>{assert.ok(!prompt.includes('<%'));assert.ok(!prompt.includes('{{'));const input=JSON.parse(prompt.split('\n').at(-1)!);assert.equal(input.changedSkills[0].raw.描述,attack);return reply()},rules);await e.compile(source,undefined,[]);});
test('显式便携传输只简化线路Schema，动作解码后仍由严格合同验证',async()=>{
 const api={async generateRaw(c:Obj){const schema=(c.json_schema as Obj).value;assert.ok(!canonical(schema).includes('anyOf'));assert.ok(!canonical(schema).includes('maxLength'));return JSON.stringify({version:EFFECT_VERSION,mappings:[{sourceId:'/技能/定量打击',disposition:'active',fidelity:mapping().fidelity,reason:'测试',actionJson:JSON.stringify(damageAction())}]})},stopGenerationById(){}};
 const model=helperCompilerModel(api,90000,'portable-action-json');const e=createCompilationEngine(model,rules);await e.compile(cleanSource(),undefined,[]);
 api.generateRaw=async()=>JSON.stringify({version:EFFECT_VERSION,mappings:[{sourceId:'/技能/定量打击',disposition:'active',fidelity:mapping().fidelity,reason:'测试',actionJson:JSON.stringify({...damageAction(),code:'evil'})}]});const converted=validateCompiled((await e.compile(cleanSource(),undefined,[])).actor);assert.equal((converted.skills[0]!.mapping.action as unknown as Obj).code,undefined);assert.doesNotThrow(()=>validateAction(converted.skills[0]!.mapping.action));
});
test('停止接口异常也只返回可处理的编译失败，不抛出计时器未捕获异常',async()=>{const model=helperCompilerModel({generateRaw:()=>new Promise(()=>{}),stopGenerationById(){throw Error('stop failed')}},5);await assert.rejects(model({prompt:'x',schema:ModelReply.json}),/停止接口异常/);});
test('跨iframe/realm的普通JSON对象可校验，访问器和自定义类拒绝',async()=>{const {runInNewContext}=await import('node:vm');const value=runInNewContext('('+JSON.stringify(damageAction())+')');assert.doesNotThrow(()=>validateAction(value));const accessor={...damageAction()};Object.defineProperty(accessor,'castMs',{get(){throw Error('must not execute')},enumerable:true});assert.throws(()=>validateAction(accessor),/访问器/);class Fake {constructor(){Object.assign(this,damageAction())}}assert.throws(()=>validateAction(new Fake()),/普通对象/);});

test('压缩的JSON Schema只引用模式节点，不把properties字典变成非法引用',async()=>{const {compactSchema}=await import('../src/host/compiler');const schema=compactSchema((await import('../src/compiler/contract')).Action.json);function walk(v:any){if(!v||typeof v!=='object')return;if(v.properties)assert.equal(Object.hasOwn(v.properties,'$ref'),false);for(const x of Object.values(v))walk(x);}walk(schema);});
