import test from 'node:test';import assert from 'node:assert/strict';
import {calculateDamage,roll,suppression,type DamageRequest} from '../src/battle/damage';
function request():DamageRequest{return {attackerLevel:9,targetLevel:9,seed:1,base:{physical:100,energy:100,mental:100,true:100},armor:{physical:2000,energy:0,mental:0},attributeReduction:{physical:.5,energy:.5,mental:0},channelMultiplier:{physical:1,energy:1,mental:1,true:1},hitChance:.9,hitRule:'guaranteed',critChance:0,critMultiplier:1.5};}
test('Lv9与Lv8成对压制：1.656与倒数；命中±13.5个百分点',()=>{const a=suppression(9,8),b=suppression(8,9);assert.ok(Math.abs(a.damageMultiplier-1.656)<1e-9);assert.ok(Math.abs(a.damageMultiplier*b.damageMultiplier-1)<1e-9);assert.ok(Math.abs(a.hitDelta-.135)<1e-9);assert.equal(b.hitDelta,-a.hitDelta);});
test('同层只有等级修正，没有额外跨层加成；不读取队伍最低等级',()=>{assert.equal(suppression(12,9).damageMultiplier,1.035**3);assert.deepEqual(suppression(9,9),{damageMultiplier:1,hitDelta:0});});
test('混合伤害逐通道减免；真实伤害绕过普通减免',()=>{const r=calculateDamage(request());assert.deepEqual(r.channels,{physical:25,energy:50,mental:100,true:100});assert.equal(r.total,275);assert.equal(r.stage,'before-shields');});
test('压制只乘一次，独立暴击倍率保留',()=>{const q=request();q.targetLevel=8;q.critChance=1;q.critMultiplier=1.7;const r=calculateDamage(q);assert.ok(r.critical);assert.ok(Math.abs(r.channels.true-100*1.656*1.7)<1e-7);});
test('普通命中有边界，绝对命中和绝对闪避不被边界抹掉',()=>{const q=request();q.attackerLevel=1;q.targetLevel=25;q.hitChance=.1;q.hitRule='normal';assert.equal(calculateDamage(q).hitChance,.05);q.hitRule='guaranteed';assert.equal(calculateDamage(q).hit,true);q.hitRule='impossible';assert.equal(calculateDamage(q).hit,false);assert.equal(calculateDamage(q).total,0);});
test('序列化随机状态可重放，不命中也消耗固定两次随机抽取',()=>{const q=request(),a=calculateDamage(q);assert.deepEqual(calculateDamage(JSON.parse(JSON.stringify(q))),a);assert.equal(a.seed,roll(roll(q.seed).seed).seed);q.hitRule='impossible';assert.equal(calculateDamage(q).seed,a.seed);});
test('全减免不产生负伤害，负输入与溢出明确拒绝',()=>{const q=request();q.attributeReduction.physical=1;assert.equal(calculateDamage(q).channels.physical,0);q.base.true=-1;assert.throws(()=>calculateDamage(q));q.base.true=Number.MAX_VALUE;q.channelMultiplier.true=Number.MAX_VALUE;assert.throws(()=>calculateDamage(q));});
