import test from 'node:test';import assert from 'node:assert/strict';
import {createBattle,advanceBattle,chooseAction,resolveAction,interruptAction,type Battle} from '../src/battle/executor';
import {card,damageAction,flat,mitigation} from './compiler-fixtures';
import type {ActionSpec} from '../src/compiler/contract';
const id='/技能/定量打击';
function fight(ally=damageAction(),enemy=damageAction()):Battle{return createBattle([{id:'a',side:'ally',card:card(ally),current:{hp:100,mp:80,sp:100},mitigation:mitigation()},{id:'e',side:'enemy',card:card(enemy),current:{hp:100,mp:80,sp:100},mitigation:mitigation()}],123)}
function next(b:Battle):Battle{return advanceBattle(b,100000).battle;}
function instant(b:Battle,actor:string,target:string):Battle{return resolveAction(chooseAction(b,actor,id,target));}
test('实际执行固定物理伤害，扣SP而非MP，并推进目标资源',()=>{const before=next(fight()),b=instant(before,'a','e');assert.equal(b.units[0]!.current.sp,90);assert.equal(b.units[0]!.current.mp,80);assert.equal(b.units[1]!.current.hp,60);assert.equal(before.units[1]!.current.hp,100);});
test('菜单和效果结算等待都不推进规则时间',()=>{let b=next(fight());assert.equal(advanceBattle(b,60000).consumedMs,0);b=chooseAction(b,'a',id,'e');assert.equal(advanceBattle(b,60000).consumedMs,0);});
test('缺少技能、非法目标或资源不足不会半扣费用/行动',()=>{const b=next(fight()),before=JSON.stringify(b);assert.throws(()=>chooseAction(b,'a','虚构','e'));assert.throws(()=>chooseAction(b,'a',id,'a'));b.units[0]!.current.sp=0;const poor=JSON.stringify(b);assert.throws(()=>chooseAction(b,'a',id,'e'));assert.equal(JSON.stringify(b),poor);assert.notEqual(before,poor);});
test('固定+百分比费用向上取整，每战次数保留',()=>{const a=damageAction();a.cost.mp={flat:3,maxFraction:.1};a.perBattleUses=1;let b=instant(next(fight(a)),'a','e');assert.equal(b.units[0]!.current.mp,69);b=instant(b,'e','a');b=next(b);assert.throws(()=>chooseAction(b,'a',id,'e'),/次数/);});
test('HP成本不能把施法者付到0',()=>{const a=damageAction();a.cost.hp.flat=100;assert.throws(()=>chooseAction(next(fight(a)),'a',id,'e'),/资源不足/);});
test('施法在确认时付费，被打断不返还资源/次数',()=>{const a=damageAction();a.castMs=1000;a.perBattleUses=1;let b=chooseAction(next(fight(a)),'a',id,'e');assert.equal(b.units[0]!.current.sp,90);b=interruptAction(b,'a');assert.equal(b.units[0]!.current.sp,90);assert.equal(b.units[0]!.used[id],1);assert.equal(Object.keys(b.commands).length,0);});
test('施法按规则时钟完成，另一方就绪权不丢失',()=>{const a=damageAction();a.castMs=1000;let b=chooseAction(next(fight(a)),'a',id,'e');b=instant(b,'e','a');b=next(b);assert.equal(b.clock.timeMs,5000);b=resolveAction(b);assert.equal(b.units[1]!.current.hp,60);});
test('护盾按明确通道吸收，不默认吞掉真伤',()=>{const a=damageAction();a.target='self';a.effects=[{op:'shield',amount:flat(30),channels:['physical'],duration:{clock:'permanent',value:0}}];const e=damageAction();e.effects=[{...e.effects[0] as Extract<ActionSpec['effects'][number],{op:'damage'}>,amounts:{physical:flat(40),energy:flat(0),mental:flat(0),true:flat(20)}}];let b=instant(next(fight(a,e)),'a','a');b=instant(b,'e','a');assert.equal(b.units[0]!.current.hp,70);assert.equal(b.units[0]!.shields.length,0);});
test('有限护盾在目标完成指定行动次数后到期，自施放不立即扣一回合',()=>{const a=damageAction();a.target='self';a.effects=[{op:'shield',amount:flat(200),channels:['physical'],duration:{clock:'target_action',value:1}}];let b=instant(next(fight(a)),'a','a');assert.equal(b.units[0]!.shields[0]!.remaining,1);b=instant(b,'e','a');b=next(b);b=instant(b,'a','a');assert.equal(b.units[0]!.shields[0]!.remaining,1);});
test('治疗按宿主有效上限截断，不凭空溢出',()=>{const a=damageAction();a.target='self';a.effects=[{op:'heal',resource:'hp',amount:flat(80)}];let b=next(fight(a));b.units[0]!.current.hp=40;b=instant(b,'a','a');assert.equal(b.units[0]!.current.hp,100);});
test('速度状态毫秒时钟：菜单不走，过期边界精确分段',()=>{const a=damageAction();a.target='self';a.effects=[{op:'speed',name:'加速',multiplier:2,chance:1,duration:{clock:'battle_time',value:1000},stack:'refresh'}];let b=instant(next(fight(a)),'a','a');assert.equal(b.clock.units[0]!.haste,2);assert.equal(advanceBattle(b,60000).consumedMs,0);b=instant(b,'e','a');b=advanceBattle(b,1000).battle;assert.equal(b.clock.timeMs,5000);assert.equal(b.clock.units[0]!.atb,50);assert.equal(b.units[0]!.speeds.length,0);assert.equal(b.clock.units[0]!.haste,1);b=advanceBattle(b,2000).battle;assert.equal(b.clock.timeMs,7000);assert.equal(b.clock.pending[0]!.unitId,'a');});
test('固定随机状态可复现，输入战斗不会被原地修改',()=>{const b=next(fight());const x=instant(b,'a','e'),y=instant(JSON.parse(JSON.stringify(b)),'a','e');assert.deepEqual(x,y);assert.equal(b.units[1]!.current.hp,100);});
test('致命伤害结束战斗并取消倒地下一个行动，不再继续攻击',()=>{const b=instant(next(fight(damageAction(1000))),'a','e');assert.equal(b.outcome,'victory');assert.equal(b.clock.pending.length,0);assert.equal(b.units[1]!.current.hp,0);assert.throws(()=>chooseAction(b,'e',id,'a'));});
test('非战斗技能无默认替补，未知效果不能构造战场',()=>{const c=card();c.skills[0]!.mapping={...c.skills[0]!.mapping,disposition:'noncombat',action:null};const entries=[{id:'a',side:'ally' as const,card:c,current:{hp:100,mp:80,sp:100},mitigation:mitigation()},{id:'e',side:'enemy' as const,card:card(),current:{hp:100,mp:80,sp:100},mitigation:mitigation()}];const b=next(createBattle(entries,1));assert.throws(()=>chooseAction(b,'a',id,'e'));(entries[1]!.card.skills[0]!.mapping.action!.effects[0] as unknown as Record<string,unknown>).op='unknown_operation';assert.throws(()=>createBattle(entries,1));});
test('目标行动时钟确实自然到期，而不是只测试重复刷新',()=>{const a=damageAction();a.target='self';a.effects=[{op:'shield',amount:flat(200),channels:['physical'],duration:{clock:'target_action',value:1}}];let b=fight(a);b.units[0]!.actions['/技能/额外测试打击']=damageAction();b=instant(next(b),'a','a');b=instant(b,'e','a');b=next(b);b=resolveAction(chooseAction(b,'a','/技能/额外测试打击','e'));assert.equal(b.units[0]!.shields.length,0);});
