import test from 'node:test';import assert from 'node:assert/strict';
import {Action,validateAction,EFFECT_VERSION,EMPTY_LIBRARY,type ActionSpec,type EffectSpec, type StatusSpec} from '../src/compiler/contract';
import {createBattle,applyBattleEffects,advanceBattle,chooseAction,resolveAction,actionUnavailable,dispatchBattleEvent,advanceExplorationEffects,costFor,legalTargets,persistentUnit as persistentUnitForTest,type Battle} from '../src/battle/executor';
import {createCompilationEngine,sourceEntries,COMPILER_ID} from '../src/compiler/engine';
import {action,mechanismLibrary,ABILITY_SAMPLES,RELIC_CATALOG,EVENT_CATALOG,targeting} from '../src/game/mechanism-content';
import {contentCard,bareMitigation,playtestParty,flat} from '../src/game/content';
import {tick as requireTick,startExpedition,restoreExpedition,eventChoice,acquireRelic,removeRelic,view,withdraw,tickExploration,useOutsideBattle} from '../src/game/expedition';
import {makeRegion} from '../src/game/region';
import {installEventFixture} from './supplier-fixture';
import {suppression} from '../src/battle/damage';
import {remainingDuration} from '../src/host/initial-states';
import {cleanSource,rules,damageAction} from './compiler-fixtures';
const guaranteed=(n:number,channel='physical'):EffectSpec=>({op:'damage',amounts:{physical:flat(channel==='physical'?n:0),energy:flat(channel==='energy'?n:0),mental:flat(channel==='mental'?n:0),true:flat(channel==='true'?n:0)},element:'none',hitChance:1,hitRule:'guaranteed',critChance:0,critMultiplier:1});
const hit=(n:number)=>action([guaranteed(n)],'enemy');
function initial(n=2):Battle {const units=Array.from({length:n},(_,i)=>({id:i?'b'+i:'a',side:i?'enemy' as const:'ally' as const,card:contentCard(1,100,10,{hit:hit(10)}),current:{hp:100,mp:65,sp:100},mitigation:bareMitigation()}));return createBattle(units,7);}
const apply=(b:Battle,a:ActionSpec,c='a',targets=['b1'])=>applyBattleEffects(b,c,a,targets);
const self=(b:Battle,a:ActionSpec,c='a')=>apply(b,a,c,[c]);
const status=(name:string,extra:Partial<StatusSpec>={}):StatusSpec=>({name,tags:[name],polarity:'positive',duration:{clock:'battle_time',value:3000},stack:'refresh',maxStacks:1,scaleWithStacks:true,priority:0,dispellable:true,removeOnDeath:false,scope:'battle',...extra});
const grant=(name:string,d:StatusSpec)=>{const a=action([{op:'apply_status',status:name}]);a.library={...EMPTY_LIBRARY(),statuses:{[name]:d}};return a;};
function act(b:Battle,a:ActionSpec,who='a',target='b1'){b.units.find(u=>u.id===who)!.actions.test=a;b.clock.pending=[{kind:'ready',unitId:who}];b.clock.units.find(u=>u.id===who)!.atb=100;return resolveAction(chooseAction(b,who,'test',target));}

test('E01–E25 数据合同：全部代表能力、60 遗物、39 事件有实际动作和完整引用',()=>{
 assert.equal(Object.keys(RELIC_CATALOG).length,61);/* 0.41：60 条随机池遗物 + 商店限定「学习装置」 */assert.equal(Object.keys(EVENT_CATALOG).length,39);
 for(const [id,a] of Object.entries(ABILITY_SAMPLES))assert.doesNotThrow(()=>validateAction(a),id);
 for(const [id,r] of Object.entries(RELIC_CATALOG))if(r.passive)assert.doesNotThrow(()=>validateAction(r.passive!),id);
 for(const event of Object.values(EVENT_CATALOG)){assert.ok(event.choices.length>=1);for(const c of event.choices)for(const r of [...c.results,...(c.risks??[]).flatMap(x=>x.results)])if(r.kind==='effect')assert.doesNotThrow(()=>validateAction(r.action),event.id);}
});
test('E01 比例/宿主系数/四通道/非致死与上下限实际计算',()=>{let b=initial();b.units[1]!.current.hp=80;const e=guaranteed(0) as Extract<EffectSpec,{op:'damage'}>;e.amounts.physical={...flat(0),subject:'target',currentResource:'hp',currentFraction:.25,lostResource:'hp',lostFraction:.5};e.amounts.true=flat(7);b=apply(b,action([e],'enemy'));assert.equal(b.units[1]!.current.hp,43);b=apply(b,action([{...guaranteed(999),lethal:false} as EffectSpec],'enemy'));assert.equal(b.units[1]!.current.hp,1);});
test('E02 多段总威力分摊、每段威力、多目标独立结算与随机重现',()=>{let b=initial(3);b=apply(b,action([{...guaranteed(30),hits:3,powerMode:'split_total',targeting:targeting('enemy','all')} as EffectSpec],'enemy'));assert.deepEqual(b.units.slice(1).map(u=>u.current.hp),[70,70]);b=apply(b,action([{...guaranteed(10),hits:3,powerMode:'per_hit'} as EffectSpec],'enemy'));assert.equal(b.units[1]!.current.hp,40);const a=action([{...guaranteed(8),targeting:{...targeting('enemy','bounce',4),allowRepeat:true}} as EffectSpec],'enemy');assert.deepEqual(apply(b,a),apply(b,a));});
test('E03–04 三资源治疗、溢出转盾、交换、燃蓝与献祭支付',()=>{let b=initial();b.units[0]!.current.hp=90;b=self(b,action([{op:'heal',resource:'hp',amount:flat(30),overflowShield:true}]));assert.equal(b.units[0]!.current.hp,100);assert.equal(b.units[0]!.shields[0]!.amount,20);b=self(b,action([{op:'resource',resource:'hp',mode:'exchange',other:'mp',amount:flat(20),ratio:1}]));assert.equal(b.units[0]!.current.hp,80);b=apply(b,action([{op:'resource',resource:'mp',mode:'burn',amount:flat(10),ratio:2,lethal:true}],'enemy'));assert.equal(b.units[1]!.current.hp,80);assert.equal(b.units[1]!.current.mp,55);const a=hit(200);a.cost.hp.flat=80;a.suicideCost=true;b=act(b,a);assert.equal(b.units[0]!.current.hp,0);assert.equal(b.units[1]!.current.hp,0);});
test('E05 次数盾按一次混合命中扣一次，普通盾FIFO，破盾时点',()=>{let b=initial();b=self(b,action([{op:'shield',amount:flat(1),charges:2,channels:['physical','energy'],duration:{clock:'permanent',value:0}}]),'b1');const e=guaranteed(10) as Extract<EffectSpec,{op:'damage'}>;e.amounts.energy=flat(10);b=apply(b,action([e],'enemy'));assert.equal(b.units[1]!.current.hp,100);assert.equal(b.units[1]!.shields[0]!.charges,1);b=apply(b,action([e],'enemy'));assert.equal(b.units[1]!.shields.length,0);b=apply(b,action([e],'enemy'));assert.equal(b.units[1]!.current.hp,80);});
test('E06 临时五维、检定、上限与费用分开，移除后恢复基础',()=>{let b=initial();b=self(b,action([{op:'modify',name:'test',duration:{clock:'battle_time',value:1000},modifiers:[{stat:'力量',flat:5},{stat:'check_strength',flat:2},{stat:'max_hp',flat:50},{stat:'cost_mp',multiplier:.5}]}]));assert.equal(b.units[0]!.attributes.力量,17);assert.equal(b.units[0]!.stats!.check_strength,2);assert.equal(b.units[0]!.max.hp,150);assert.equal(costFor(b.units[0]!,action([guaranteed(1)],'enemy',10)).mp,5);b=advanceBattle(b,1000).battle;assert.equal(b.units[0]!.max.hp,100);assert.equal(b.units[0]!.attributes.力量,12);});
test('E07 必中必闪按优先级和次数覆盖，E08穿甲/真实/元素免疫',()=>{let b=initial();b=self(b,action([{op:'rule',rule:'guaranteed_evade',key:'*',duration:{clock:'permanent',value:0},uses:1,priority:10}]),'b1');b=apply(b,hit(20));assert.equal(b.units[1]!.current.hp,100);b=apply(b,hit(20));assert.equal(b.units[1]!.current.hp,80);b=self(b,action([{op:'rule',rule:'immune_element',key:'火',duration:{clock:'permanent',value:0},uses:1,priority:5}]),'b1');const e=guaranteed(10) as Extract<EffectSpec,{op:'damage'}>;e.element='火';e.amounts.energy=flat(10);b=apply(b,action([e],'enemy'));assert.equal(b.units[1]!.current.hp,80);b=apply(b,action([e],'enemy'));assert.equal(b.units[1]!.current.hp,60);});
test('E09–10 状态叠层、独立实例、优先级净化和偷取',()=>{let b=initial();const a=grant('stack',status('stack',{stack:'stack',maxStacks:3,scaleWithStacks:true,modifiers:[{stat:'力量',flat:2}]}));b=self(b,a);b=self(b,a);assert.equal(b.units[0]!.statuses![0]!.stacks,2);assert.equal(b.units[0]!.attributes.力量,16);b=apply(b,action([{op:'dispel',mode:'steal',polarity:'positive',count:1}],'enemy'),'b1',['a']);assert.equal(b.units[0]!.statuses!.length,0);assert.equal(b.units[1]!.statuses![0]!.stacks,2);});
test('E11 DOT与护盾/死亡豁免组合；菜单时钟停止',()=>{let b=initial();b.units[1]!.current.hp=10;b=self(b,ABILITY_SAMPLES.undying!,'b1');b=self(b,action([{op:'shield',amount:flat(5),channels:['true'],duration:{clock:'permanent',value:0}}]),'b1');b=apply(b,ABILITY_SAMPLES.poison!);b=advanceBattle(b,1000).battle;assert.equal(b.units[1]!.current.hp,7);b.clock.pending=[{kind:'ready',unitId:'a'}];b.clock.units[0]!.atb=100;const copy=structuredClone(b);b=advanceBattle(b,99999).battle;assert.equal(b.clock.timeMs,copy.clock.timeMs);b.clock.pending=[];b=advanceBattle(b,1000).battle;assert.ok(b.units[1]!.current.hp>0);});
test('E12 各控制与ATB/施法/阵营/受击唤醒实际作用',()=>{for(const control of ['stun','freeze','sleep']){let b=initial();b=apply(b,ABILITY_SAMPLES[control]!);b=advanceBattle(b,1000).battle;assert.equal(b.clock.units[1]!.atb,0,control);assert.ok(b.clock.units[0]!.atb>0);}let b=apply(initial(),ABILITY_SAMPLES.silence!);b.units[1]!.actions.spell={...hit(1),category:'spell'};assert.match(actionUnavailable(b,b.units[1]!,'spell'),/沉默/);b=apply(initial(),ABILITY_SAMPLES.sleep!);b=apply(b,hit(1));assert.equal(b.units[1]!.statuses?.length,0);});
test('E13 嘲讽/隐匿/标记和守护实际改变可选目标',()=>{let b=initial(3);b=self(b,ABILITY_SAMPLES.hidden!,'b1');assert.deepEqual(legalTargets(b,b.units[0]!,hit(2)).map(u=>u.id),['b2']);const mark={...ABILITY_SAMPLES.mark!,targeting:targeting('enemy','all')};b=apply(b,mark);assert.equal(legalTargets(b,b.units[0]!,hit(2)).length,2);});
test('E14–16推退条/额外行动/打断/费用不返还/封锁与次数重置',()=>{let b=initial();b=self(b,action([{op:'atb',mode:'immediate',value:100}]));assert.equal(b.clock.pending[0]!.unitId,'a');const cast={...hit(10),castMs:2000,perBattleUses:1,cost:{hp:{flat:0,maxFraction:0},mp:{flat:10,maxFraction:0},sp:{flat:0,maxFraction:0}}};b.units[0]!.actions.cast=cast;b=chooseAction(b,'a','cast','b1');assert.equal(b.units[0]!.current.mp,55);/* 0.21：打断是强控，对同级可当场抵抗；这里验证费用不返还，打断者高1级（必定生效） */b.units[1]!.level+=1;b=apply(b,action([{op:'cast',mode:'interrupt',value:0}],'enemy'),'b1',['a']);assert.equal(b.clock.units[0]!.cast,null);assert.equal(b.units[0]!.current.mp,55);assert.match(actionUnavailable(b,b.units[0]!,'cast'),/次数/);b=self(b,action([{op:'uses',mode:'reset',skill:'cast',value:0}]));assert.equal(actionUnavailable(b,b.units[0]!,'cast'),'');});
test('E17 反射/反击不互相无限触发；分担按实际来源与护盾结算',()=>{let b=initial();b=self(b,ABILITY_SAMPLES.react!);b=self(b,ABILITY_SAMPLES.react!,'b1');b=apply(b,hit(10));assert.ok(b.log.length<100);assert.ok(Number.isFinite(b.units[0]!.current.hp));let c=initial(3);c.units[2]!.side='enemy';const g=grant('share',status('share',{reactions:[{kind:'share',fraction:.5,target:'source'}]}));g.target='ally';c=apply(c,g,'b2',['b1']);c=apply(c,hit(20));assert.equal(c.units[1]!.current.hp,90);assert.equal(c.units[2]!.current.hp,90);});
test('E18先豁免后全灭；复苏不被普通治疗冒充；高阶处决',()=>{let b=self(initial(),ABILITY_SAMPLES.undying!,'b1');b=apply(b,hit(200));assert.ok(b.units[1]!.current.hp>0);b=apply(b,hit(200));assert.equal(b.units[1]!.current.hp,0);b=apply(b,ABILITY_SAMPLES.revive!,'b1',['b1']);assert.equal(b.units[1]!.current.hp,30);let c=self(initial(),ABILITY_SAMPLES.undying!,'b1');c.units[0]!.level=2;/* 高阶处决：处决只对低等级目标生效 */c=apply(c,ABILITY_SAMPLES.execution!);assert.equal(c.units[1]!.current.hp,0);});
test('E19召唤继承/独立行动条/名额/召回/召唤者死亡',()=>{let b=self(initial(),ABILITY_SAMPLES.familiar!);const u=b.units.find(u=>u.owner==='a')!;assert.equal(u.level,1);assert.equal(u.max.hp,40);assert.ok(b.clock.units.some(c=>c.id===u.id));b=self(b,ABILITY_SAMPLES.familiar!);b=self(b,ABILITY_SAMPLES.familiar!);assert.equal(b.units.filter(u=>u.owner==='a').length,2);b=apply(b,hit(500),'b1',['a']);assert.ok(b.units.filter(u=>u.owner==='a').every(u=>u.current.hp===0));});
test('E20场域覆盖/定时清理，E21时停/延后/有限回溯/空间隔离',()=>{let b=self(initial(),ABILITY_SAMPLES.weather!);assert.equal(b.fields!.length,1);b=self(b,ABILITY_SAMPLES.no_heal!);assert.equal(b.fields!.length,1);assert.ok(b.fields![0]!.definition.endsWith('::suppression'));b=self(b,ABILITY_SAMPLES.snapshot!);b=apply(b,hit(20),'b1',['a']);b=self(b,ABILITY_SAMPLES.rewind!);assert.equal(b.units[0]!.current.hp,100);b=apply(b,ABILITY_SAMPLES.stop_time!);b=advanceBattle(b,1000).battle;assert.equal(b.clock.units[1]!.atb,0);});
test('E22许可复制与伤害通道转化，E23概念封印及优先级',()=>{let b=initial();b.units[1]!.actions.copyme=hit(5);b=apply(b,action([{op:'copy',mode:'skill',id:'copyme',duration:{clock:'battle_time',value:1000}}],'enemy'));assert.ok(b.units[0]!.actions['copy:b1:copyme']);b=apply(b,ABILITY_SAMPLES.sealing!);b.units[1]!.actions.magic={...hit(5),category:'spell'};assert.match(actionUnavailable(b,b.units[1]!,'magic'),/封印/);const conversion=grant('convert',status('convert',{reactions:[{kind:'convert',fromChannel:'physical',toChannel:'true',fraction:1}]}));b=self(b,conversion);b.units[1]!.base!.mitigation.armor.physical=999999;b=apply(b,hit(10));assert.equal(b.units[1]!.current.hp,90);});
test('E24–25 / S01事件代价、带权风险、分支、遗物选择与存档不重扣',()=>{const s=startExpedition(playtestParty(),7);const event=EVENT_CATALOG['E019']!;const t=installEventFixture(s);s.mode='event';s.eventState={id:event.id,thingId:t.id,offers:[],results:[],owner:s.party[0]!.id,choice:''};eventChoice(s,0);assert.ok(s.eventState!.offers.length);const paid=s.party[0]!.current.hp;const restored=restoreExpedition(s);restored.paused=false;eventChoice(restored,0);assert.equal(restored.ownedRelics!.length,1);assert.equal(restored.mode,'explore');assert.ok(restored.party[0]!.current.hp<=paid+50);assert.ok(Object.keys(restored.eventJournal!).length===1);});
test('S02 全来源增量编译覆盖、耗品数量不入语义、属性更新零额外请求',async()=>{const source=cleanSource();source.装备={环:{效果:'触发治疗'}};source.状态定义={再生:{效果:'持续治疗'}};source.种族特性={韧性:'拥有一次死亡豁免'};source.登神长阶={是否开启:true,要素:{火:'火焰免疫'}};source.道具定义={药:{效果:'恢复生命'}};let calls=0;const engine=createCompilationEngine(async req=>{calls++;const input=JSON.parse(req.prompt.slice(req.prompt.lastIndexOf('\n')+1));return {version:EFFECT_VERSION,mappings:input.changedSkills.map((x:any)=>({sourceId:x.sourceId,fidelity:{mode:'exact',summary:'合成结构回归；不是模型语义证明',changes:[],clauses:[{original:JSON.stringify(x.raw),implementation:'对应测试动作'}]},disposition:x.sourceId.startsWith('/状态定义/')?'passive':'active',reason:'输入来源的确定性机制夹具映射（非实模型语义证明）',action:x.sourceId.startsWith('/状态定义/')?grant('native',status('native',{scope:'host',modifiers:[{stat:'力量',flat:1}]})):damageAction()}))};},rules);const first=await engine.compile(source,undefined,[]);assert.equal((first.actor as any).skills.length,sourceEntries(source,rules).length);source.属性={力量:20,敏捷:10,体质:10,智力:10,精神:10};await engine.compile(source,first.actor,[]);assert.equal(calls,1);});
test('S04所有战斗状态JSON恢复同种子同操作同结果；探索时钟不追算现实等待',()=>{let b=self(initial(),ABILITY_SAMPLES.familiar!);b=self(b,ABILITY_SAMPLES.weather!);b=apply(b,ABILITY_SAMPLES.poison!);const other=JSON.parse(JSON.stringify(b));assert.deepEqual(advanceBattle(b,500),advanceBattle(other,500));const s=startExpedition(playtestParty(),9),r=restoreExpedition(s);assert.equal(r.paused,true);assert.equal(r.region.id,s.region.id);tickExploration(r,100000);assert.equal(r.explorationMs,0);assert.deepEqual(remainingDuration('8小时'),{clock:'battle_time',value:28800000});});
test('S05分批离场与全灭保留既有账本规则，不保留临时构筑',()=>{const s=startExpedition(playtestParty(),8);acquireRelic(s,'R020',s.party[0]!.id);withdraw(s,[s.party[0]!.id]);assert.equal(s.run.status,'active');assert.equal(s.run.participants[0]!.status,'voluntaryExit');withdraw(s);assert.equal(s.run.status,'success');assert.equal(s.ownedRelics!.length,0);assert.ok(s.party.every(p=>!p.persistent));});
test('S06新区域宝箱类总8%（真4%/怪4%）、无限深度、超25挑战压制',()=>{let count=0;for(let seed=0;seed<1000;seed++)if(makeRegion(1,0,seed).things.some(t=>t.kind==='chest'||t.kind==='mimic'))count++;assert.ok(count>40&&count<120,String(count));assert.equal(makeRegion(999,2,3).depth,999);assert.ok(suppression(33,25).damageMultiplier>suppression(26,25).damageMultiplier);const s=startExpedition(playtestParty(),7,5,['anchor-5']);assert.equal(s.depth,5);/* 2026-09-28：已移除返回浅层 */});
test('S07 四人/召唤物、多目标、分类、不可用原因和状态信息来自同一运行态',()=>{const party=playtestParty();party.push({...structuredClone(party[0]!),id:'third',name:'第三人'},{...structuredClone(party[1]!),id:'fourth',name:'第四人'});const s=startExpedition(party,99);s.mode='battle';s.encounterId=s.region.things.find(t=>t.kind==='enemy')!.id;s.battle=createBattle([...party.map(p=>({id:p.id,name:p.name,side:'ally' as const,card:p.card,current:p.current,mitigation:bareMitigation()})),{id:'enemy-0',side:'enemy',card:contentCard(1,100,10,{hit:hit(1)}),current:{hp:100,mp:65,sp:100},mitigation:bareMitigation()}],7);s.battle=self(s.battle,ABILITY_SAMPLES.familiar!,'reader');s.battle.clock.pending=[{kind:'ready',unitId:'reader'}];s.battle.clock.units[0]!.atb=100;const v=view(s);assert.equal(v.party.length,4);assert.equal(v.battle.units.filter(u=>u.owner).length,1);assert.ok(v.battle.actions.some(a=>a.id==='booksea:guard'));assert.ok(v.battle.actions.every(a=>'reason' in a));});

test('S03多段分别触发反射；后续按实际总伤害恢复，而非原始值或最后一段',()=>{let b=initial();b.units[0]!.current.hp=50;b=self(b,grant('reflect-only',status('reflect-only',{reactions:[{kind:'reflect',fraction:.25,basis:'actual'}]})),'b1');const a=action([{...guaranteed(20),hits:3,powerMode:'split_total'} as EffectSpec,{op:'heal',resource:'hp',amount:{...flat(0),eventFraction:1},targeting:targeting('self')}],'enemy');b=apply(b,a);assert.equal(b.units[1]!.current.hp,82);assert.equal(b.units[0]!.current.hp,65);assert.equal(b.log.filter(l=>l.kind==='damage'&&l.unit==='a').length,3);});
test('E06 固定费用折扣加百分比折扣，减至零不会反向增加资源',()=>{let b=self(initial(),action([{op:'modify',name:'cost',duration:{clock:'permanent',value:0},modifiers:[{stat:'cost_mp',flat:-4,multiplier:.5}]}]));assert.equal(costFor(b.units[0]!,action([guaranteed(1)],'enemy',10)).mp,3);assert.equal(costFor(b.units[0]!,action([guaranteed(1)],'enemy',2)).mp,0);});
test('E10高等级净化者转移指定层数，来源归属保持正确',()=>{let b=initial(3);b.units[0]!.level=2;const a=grant('stacks',status('stacks',{stack:'stack',maxStacks:5}));a.effects[0]={op:'apply_status',status:'stacks',stacks:3};b=self(b,a,'b1');b=apply(b,action([{op:'dispel',mode:'transfer',recipient:'selected_other',polarity:'positive',stacks:1,count:1,targeting:{side:'any',selection:'manual',count:1}}],'enemy'),'a',['b1','b2']);assert.equal(b.units[1]!.statuses![0]!.stacks,2);assert.equal(b.units[2]!.statuses![0]!.stacks,1);});
test('E16按行动封锁不会当成毫秒，且完成指定行动后解除',()=>{let b=self(initial(),action([{op:'uses',mode:'seal',skill:'hit',value:0,duration:{clock:'target_action',value:2}}]));b=advanceBattle(b,1000).battle;assert.match(actionUnavailable(b,b.units[0]!,'hit'),/封锁/);b=act(b,action([{op:'atb',mode:'set',value:0}]),'a','a');assert.match(actionUnavailable(b,b.units[0]!,'hit'),/封锁/);b=act(b,action([{op:'atb',mode:'set',value:0}]),'a','a');assert.equal(actionUnavailable(b,b.units[0]!,'hit'),'');});
test('E19替身承伤后死亡；召唤物耗尽技能资源仍可待机',()=>{let b=self(initial(),ABILITY_SAMPLES.substitute!);const s=b.units.find(u=>u.owner==='a')!;assert.ok(s.actions['booksea:wait']);b=apply(b,hit(200),'b1',['a']);assert.equal(b.units[0]!.current.hp,100);assert.equal(b.units.find(u=>u.id===s.id)!.current.hp,0);});
test('E21延迟复苏保留结算窗口，不先宣告全灭',()=>{let b=initial();const a=action([{op:'time',mode:'delay',key:'revive',duration:{clock:'battle_time',value:500},action:'rise',restore:[]}]);a.library={...EMPTY_LIBRARY(),actions:{rise:{...action([{op:'revive',amount:flat(20)}]),targeting:{side:'self',selection:'manual',count:1,life:'downed'}}}};b=self(b,a);b=apply(b,hit(500),'b1',['a']);b=advanceBattle(b,1).battle;assert.equal(b.outcome,'active');b=advanceBattle(b,499).battle;assert.equal(b.units[0]!.current.hp,20);assert.equal(b.clock.units[0]!.active,true);});
test('E21探索时钟精确执行多个周期和延迟；不推进战斗时钟状态',()=>{let b=initial();b.units[0]!.current.hp=40;const a=grant('out',status('out',{scope:'run',duration:{clock:'exploration_time',value:5000},tick:{clock:'exploration_time',interval:1000,count:3,action:'pulse'}}));a.library!.actions.pulse=action([{op:'heal',resource:'hp',amount:flat(5)}]);b=self(b,a);b=self(b,grant('battle',status('battle')));b=advanceExplorationEffects(b,3000);assert.equal(b.units[0]!.current.hp,55);assert.equal(b.units[0]!.statuses!.find(s=>s.definition.name==='battle')!.remaining,3000);assert.equal(b.units[0]!.statuses!.find(s=>s.definition.name==='out')!.tickCount,3);});
test('E22复制带库动作可执行，不只复制按钮；不许可道具拒绝复制',()=>{let b=initial();b.units[1]!.actions.librarySkill=grant('copied-status',status('copied-status',{modifiers:[{stat:'力量',flat:7}]}));b=apply(b,action([{op:'copy',mode:'skill',id:'librarySkill',duration:{clock:'battle_time',value:3000}}],'enemy'));const copied=b.units[0]!.actions['copy:b1:librarySkill']!;b=self(b,copied);assert.equal(b.units[0]!.attributes.力量,19);b.units[1]!.actions.item={...hit(1),copyable:false};b=apply(b,action([{op:'copy',mode:'skill',id:'item',duration:{clock:'battle_time',value:3000}}],'enemy'));assert.equal(b.units[0]!.actions['copy:b1:item'],undefined);});
test('E23因果绑定使用明确键；同级更快的必中压过必闪',()=>{let b=self(initial(),ABILITY_SAMPLES.causality!);b.clock.units[0]!.haste=2;b=self(b,action([{op:'rule',rule:'guaranteed_evade',key:'*',priority:10,uses:1,duration:{clock:'permanent',value:0}}]),'b1');b.clock.units[0]!.haste=2;b=apply(b,hit(10));assert.equal(b.units[1]!.current.hp,90);assert.throws(()=>validateAction(action([{op:'rule',rule:'causality',key:'make_up_anything',duration:{clock:'permanent',value:0}}])),/因果键/);});
test('M10查询、菜单、暂停重复调用不改变运行态或随机状态',()=>{const s=startExpedition(playtestParty(),17);const before=JSON.stringify(s);for(let n=0;n<20;n++)view(s);assert.equal(JSON.stringify(s),before);const b=initial();for(let n=0;n<20;n++){actionUnavailable(b,b.units[0]!,'hit');legalTargets(b,b.units[0]!,hit(1));}assert.equal(b.seed,7);});
test('M11每件遗物可获得、在战场具现并移除，源卡与永久数据不变',()=>{for(const id of Object.keys(RELIC_CATALOG)){const s=startExpedition(playtestParty(),31),before=structuredClone(s.party.map(p=>p.card));acquireRelic(s,id,s.party[0]!.id);assert.ok(s.ownedRelics!.some(x=>x.id===id),id);if(RELIC_CATALOG[id]!.passive)assert.ok(s.world!.units.some(u=>u.passiveNames?.some(name=>name===RELIC_CATALOG[id]!.name)),id);const owner=s.ownedRelics![0]!.owner;removeRelic(s,id,owner);assert.equal(s.ownedRelics!.length,RELIC_CATALOG[id]!.droppable?0:1,id);assert.deepEqual(s.party.map(p=>p.card),before,id);}});
test('M11全部 39 事件的每个选项可执行并序列化（含拾取 / 挑战 / 传送 / 撤离）',()=>{let count=0;for(const e of Object.values(EVENT_CATALOG))for(let choice=0;choice<e.choices.length;choice++){
 const party=playtestParty().slice(0,1);party[0]!.card.numeric.max={hp:10000,mp:10000,sp:10000};party[0]!.current={...party[0]!.card.numeric.max};let s=startExpedition(party,choice+7);s.world!.units[0]!.exploration=[{kind:'event_option',value:1,clock:'permanent',remaining:0}];s.mode='event';s.eventState={id:e.id,thingId:installEventFixture(s).id,offers:[],results:[],owner:s.party[0]!.id,choice:''};eventChoice(s,choice);
 s=restoreExpedition(JSON.parse(JSON.stringify(s)));s.paused=false;
  for(let i=0;i<12&&s.mode!=='explore'&&s.mode!=='ended';i++){
   if(s.mode==='event'){const v=view(s).event!;if(s.eventPick){const confirm=v.choices.findIndex(c=>c.id==='confirm');if(confirm>=0&&s.eventPick.selected.length)eventChoice(s,confirm);else eventChoice(s,0);}else if(s.eventState!.offers.length)eventChoice(s,0);else{const leave=EVENT_CATALOG[s.eventState!.id]?.choices.findIndex(c=>c.id==='leave')??-1;eventChoice(s,leave>=0?leave:0);}}
  if(s.mode==='battle'){s.battle=apply(s.battle!,action([{...guaranteed(100000),targeting:targeting('enemy','all')} as EffectSpec],'enemy'),s.party[0]!.id,s.battle!.units.filter(u=>u.side==='enemy').map(u=>u.id));s.battle=advanceBattle(s.battle,1).battle;requireTick(s);}
 }
  assert.ok(s.mode==='explore'||s.mode==='ended',e.id+':'+choice);count++;
  }assert.equal(count,Object.values(EVENT_CATALOG).reduce((n,e)=>n+e.choices.length,0));
});
test('S04事件给予的运行期状态及其动作库进入下一战仍有效，无丢失引用',()=>{const p=playtestParty().slice(0,1),s=startExpedition(p,77);const a=grant('run-poison',status('run-poison',{polarity:'negative',scope:'run',duration:{clock:'battle_time',value:3000},tick:{clock:'battle_time',interval:1000,count:3,action:'dot'}}));a.library!.actions.dot=action([guaranteed(7,'true')]);s.world=self(s.world!,a,p[0]!.id);const original=s.world.units[0]!;const pc=persistentUnitForTest(original);let b=createBattle([{id:original.id,side:'ally',card:p[0]!.card,current:original.current,persistent:pc,mitigation:bareMitigation()},{id:'b1',side:'enemy',card:contentCard(1,100,10,{hit:hit(1)}),current:{hp:100,mp:60,sp:100},mitigation:bareMitigation()}],4);const hp=b.units[0]!.current.hp;b=advanceBattle(b,1000).battle;assert.equal(b.units[0]!.current.hp,hp-7);});
test('S04相同库内ID的两个来源互不覆盖，状态保存不复制整份未用目录',()=>{const card=contentCard(1,100,10,{one:grant('buff',status('first',{modifiers:[{stat:'力量',flat:3}]})),two:grant('buff',status('second',{modifiers:[{stat:'力量',flat:5}]}))});let b=createBattle([{id:'a',side:'ally',card,current:{hp:100,mp:60,sp:100},mitigation:bareMitigation()},{id:'b1',side:'enemy',card:contentCard(1,100,10,{hit:hit(1)}),current:{hp:100,mp:60,sp:100},mitigation:bareMitigation()}],7);b=act(b,b.units[0]!.actions.one!,'a','a');assert.equal(b.units[0]!.attributes.力量,15);b=act(b,b.units[0]!.actions.two!,'a','a');assert.equal(b.units[0]!.attributes.力量,20);const s=startExpedition(playtestParty(),5);acquireRelic(s,'R001',s.party[0]!.id);assert.ok(JSON.stringify(s).length<200000);});
test('E16零初始充能不可施放，获得充能后按次扣除；零恢复显式动作可再就绪',()=>{let b=initial();b.units[0]!.actions.charged={...hit(1),charges:0};b.units[0]!.charges={charged:0};assert.match(actionUnavailable(b,b.units[0]!,'charged'),/蓄能/);b=self(b,action([{op:'uses',mode:'charge',skill:'charged',value:1}]));assert.equal(actionUnavailable(b,b.units[0]!,'charged'),'');const a={...b.units[0]!.actions.charged!,recoveryFactor:0};b.units[0]!.charges!.test=1;b=act(b,a);assert.equal(b.units[0]!.charges!.test,0);assert.equal(b.clock.units[0]!.atb,100);});
test('E24探索感知可见敌群和宝箱信息，危险减免改变事件实际伤害',()=>{const s=startExpedition(playtestParty(),7);s.world=self(s.world!,ABILITY_SAMPLES.scout!,s.party[0]!.id);assert.ok(view(s).explorationIntel.enemies.length>0);assert.notEqual(view(s).explorationIntel.chests,null);let b=self(initial(),ABILITY_SAMPLES.omen!,'b1');b=apply(b,{...hit(20),category:'event_hazard'});assert.equal(b.units[1]!.current.hp,86);});
test('M10开发版拒绝旧未决事件，不迁移、不猜选项、不加载扣费',()=>{const s=startExpedition(playtestParty(),8);delete s.mechanicsVersion;s.mode='event';delete s.eventState;const before=JSON.stringify(s);assert.throws(()=>restoreExpedition(s),/不迁移旧档/);assert.equal(JSON.stringify(s),before);});
test('E01同一伤害通道混合施法者五维与目标最大资源，合并结算护盾与防御',()=>{let b=initial();b.units[0]!.max.hp=300;const e=guaranteed(0) as Extract<EffectSpec,{op:'damage'}>;e.amounts.physical={...flat(0),attribute:'力量',factor:1,subject:'caster',resourceSubject:'target',maxResource:'hp',maxFraction:.1};b=apply(b,action([e],'enemy'));assert.equal(b.units[1]!.current.hp,78);});
test('E09明确不按层数缩放的状态保留计层但不翻倍数值',()=>{let b=initial();const a=grant('flat',status('flat',{stack:'stack',maxStacks:3,scaleWithStacks:false,modifiers:[{stat:'力量',flat:2}]}));b=self(self(b,a),a);assert.equal(b.units[0]!.statuses![0]!.stacks,2);assert.equal(b.units[0]!.attributes.力量,14);});
test('S04跨战斗保留触发冷却的相对剩余时间，而非复用旧时钟绝对值',()=>{let b=initial();const a=grant('retained',status('retained',{scope:'run',duration:{clock:'permanent',value:0}}));b=self(b,a);b.units[0]!.statuses![0]!.last.cooldown=900;const p=persistentUnitForTest(b.units[0]!,1200);assert.equal(p.statuses![0]!.last.cooldown,-300);assert.equal(b.units[0]!.statuses![0]!.last.cooldown,900);});
test('E08双语常规元素使用同一身份，火抗与火免疫不是fire/火两套机制',()=>{let b=self(initial(),action([{op:'element_resist',element:'fire',multiplier:.5}]),'b1');b=apply(b,action([{...guaranteed(20),element:'火'} as EffectSpec],'enemy'));assert.equal(b.units[1]!.current.hp,90);b.units[1]!.level=2;b=self(b,action([{op:'rule',rule:'immune_element',key:'fire',uses:1,duration:{clock:'permanent',value:0}}]),'b1');b=apply(b,action([{...guaranteed(20),element:'火'} as EffectSpec],'enemy'));assert.equal(b.units[1]!.current.hp,90);});
test('E04资源加减/交换不可冒充复活，倒地HP只由revive改变',()=>{for(const mode of ['add','set','swap'] as const){let b=initial();b.units[1]!.current.hp=0;b.units[1]!.deadHandled=true;b=apply(b,action([{op:'resource',mode,resource:'hp',amount:flat(20),targeting:{...targeting('enemy'),life:'downed'}}],'enemy'));assert.equal(b.units[1]!.current.hp,0,mode);}});
test('E16探索计时封锁按实际探索毫秒到期，永久封锁不受此计时影响',()=>{let b=initial();b=self(b,action([{op:'uses',skill:'hit',mode:'seal',value:1,duration:{clock:'exploration_time',value:1000}}]));b=advanceExplorationEffects(b,999);assert.match(actionUnavailable(b,b.units[0]!,'hit'),/封锁/);b=advanceExplorationEffects(b,1);assert.equal(actionUnavailable(b,b.units[0]!,'hit'),'');});
test('S04高等级偷取周期状态携带原定义图，原单位不在新战斗仍按新执行归属运行',()=>{let b=initial();b.units[0]!.level=2;const a=grant('hot',status('hot',{scope:'run',tick:{clock:'battle_time',interval:1000,count:3,action:'tick'}}));a.library!.actions.tick=action([{op:'heal',resource:'hp',amount:flat(7)}]);b=self(b,a,'b1');b=apply(b,action([{op:'dispel',mode:'steal',polarity:'positive',count:1}],'enemy'));const persistent=persistentUnitForTest(b.units[0]!);let next=createBattle([{id:'a',side:'ally',card:contentCard(1,100,10,{hit:hit(1)}),current:{hp:50,mp:10,sp:10},mitigation:bareMitigation(),persistent},{id:'new',side:'enemy',card:contentCard(1,100,10,{hit:hit(1)}),current:{hp:100,mp:10,sp:10},mitigation:bareMitigation()}],2);next=advanceBattle(next,1000).battle;assert.equal(next.units[0]!.current.hp,57);});
test('E22具名动作引用可复制已命名空间绑定的授予技能，不复制系统命令',()=>{let b=initial();const a=action([]);a.library={...EMPTY_LIBRARY(),actions:{counter:{...hit(7),copyable:true}}};a.grantedActions=['counter'];const card=contentCard(1,100,10,{grant:a});b=createBattle([{id:'a',side:'ally',card:contentCard(1,100,10,{hit:hit(1)}),current:{hp:100,mp:10,sp:10},mitigation:bareMitigation()},{id:'b1',side:'enemy',card,current:{hp:100,mp:10,sp:10},mitigation:bareMitigation()}],1);b=apply(b,action([{op:'copy',mode:'skill',id:'counter',duration:{clock:'battle_time',value:1000}}],'enemy'));assert.ok(b.units[0]!.actions['copy:b1:counter']);});
test('E11同一步末尾新施加/刷新的状态不被扣除施加前的一秒',()=>{let b=initial();const a=grant('pulse',status('pulse',{tick:{clock:'battle_time',interval:1000,count:2,action:'tick'}}));a.library!.actions.tick=action([{op:'apply_status',status:'mark',targeting:targeting('enemy','all')}],'enemy');a.library!.statuses.mark=status('mark',{duration:{clock:'battle_time',value:1000}});b=self(b,a);b=advanceBattle(b,1000).battle;assert.equal(b.units[1]!.statuses![0]!.remaining,1000);b=advanceBattle(b,1000).battle;assert.equal(b.units[1]!.statuses![0]!.remaining,1000);});
test('M08深层缩放不会撞上旧合同的一万亿人为上限',async()=>{const {scaleEnemyAction}=await import('../src/game/combat-ai');const a=scaleEnemyAction(hit(40),1000);assert.doesNotThrow(()=>validateAction(a));assert.ok((a.effects[0] as Extract<EffectSpec,{op:'damage'}>).amounts.physical.flat>1e12);});
test('S04运行时立即保存入场状态，释放旧视图前保存最后规则帧',async()=>{const {mountExpeditionRuntime}=await import('../src/game/runtime');const values=new Map<string,string>(),timers:Function[]=[];const win={localStorage:{getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>values.set(k,v)},setInterval:(f:Function)=>{timers.push(f);return timers.length;},clearInterval:()=>{},document:{hidden:false,addEventListener:()=>{},removeEventListener:()=>{}},addEventListener:()=>{},removeEventListener:()=>{}} as unknown as Window;const runtime=mountExpeditionRuntime({storageKey:'test',initial:startExpedition(playtestParty(),1)},win);assert.ok(values.get('test'));runtime.attach(raw=>{const frame=JSON.parse(raw);runtime.rendered(frame.mode,frame.region?.id);});timers[0]!();assert.equal(JSON.parse(values.get('test')!).explorationMs,0);runtime.dispose();assert.equal(JSON.parse(values.get('test')!).explorationMs,50);});
test('E09跨来源同类强度组明确声明时覆盖，不混淆默认来源边界',()=>{let b=initial();const weak=grant('buff',status('weak',{stack:'strongest',stackGroup:'shared',modifiers:[{stat:'力量',flat:2}]})),strong=grant('buff',status('strong',{stack:'strongest',stackGroup:'shared',modifiers:[{stat:'力量',flat:5}]}));b=self(b,weak);strong.target='enemy';b=applyBattleEffects(b,'b1',strong,['a']);assert.equal(b.units[0]!.attributes.力量,17);assert.equal(b.units[0]!.statuses!.length,1);});
test('E04生命交换是否可自杀由lethal明确控制',()=>{for(const lethal of [false,true]){let b=initial();b.units[1]!.current.mp=0;b=apply(b,action([{op:'resource',mode:'swap',resource:'mp',other:'hp',amount:flat(0),lethal}],'enemy'));assert.equal(b.units[0]!.current.hp,lethal?0:1);}});
test('M09正文未连接不登记已请求，连接后显式交接只触发一次',async()=>{const {requestNarrativeOnce}=await import('../src/host/narrative');let vars:any={booksea:{}},calls=0;const h={getVariables:()=>vars,getLastMessageId:()=>calls,getChatMessages:()=>[{role:calls?'assistant':'user',message:'正文'}],updateVariablesWith:async(fn:any)=>{vars=fn(vars);},triggerSlash:async(cmd:string)=>{assert.equal(cmd,'/trigger await=true');calls++;}},context={onlineStatus:'no_connection',saveChat:async()=>{}};await assert.rejects(requestNarrativeOnce(h,context,'exit:test'),/未连接/);assert.equal(vars.booksea.narrativeRequests,undefined);context.onlineStatus='connected';await requestNarrativeOnce(h,context,'exit:test');await requestNarrativeOnce(h,context,'exit:test');assert.equal(calls,1);});
test('E19召唤按战斗时钟到期后继续推进，不留下零时长死循环',()=>{const a=structuredClone(ABILITY_SAMPLES.familiar!);for(const t of Object.values(a.library!.summons))t.duration={clock:'battle_time',value:100};let b=self(initial(),a);const id=b.units.find(u=>u.owner==='a')!.id;b=advanceBattle(b,200).battle;assert.equal(b.clock.timeMs,200);assert.equal(b.units.find(u=>u.id===id)!.current.hp,0);});
test('E16行动中刷新封锁不扣除刚刷新的本次行动',()=>{let b=self(initial(),action([{op:'uses',skill:'hit',mode:'seal',value:1,duration:{clock:'target_action',value:1}}]));b=act(b,action([{op:'uses',skill:'hit',mode:'seal',value:1,duration:{clock:'target_action',value:2}}]),'a','a');assert.equal(b.units[0]!.sealed!.hit,2);});
test('E05/14/22探索护盾加速与复制计时跨遭遇保留，战斗内冻结，探索精确到期',()=>{const d={clock:'exploration_time' as const,value:1000};let b=self(initial(),action([{op:'shield',amount:flat(20),channels:['physical'],duration:d},{op:'speed',name:'speed',multiplier:2,chance:1,duration:d,stack:'refresh'}]));b=apply(b,action([{op:'copy',mode:'skill',id:'hit',duration:d}],'enemy'));b=advanceExplorationEffects(b,250);const p=persistentUnitForTest(b.units[0]!);let next=createBattle([{id:'a',side:'ally',card:contentCard(1,100,10,{hit:hit(10)}),current:{hp:100,mp:65,sp:100},mitigation:bareMitigation(),persistent:p},{id:'b1',side:'enemy',card:contentCard(1,100,10,{hit:hit(10)}),current:{hp:100,mp:65,sp:100},mitigation:bareMitigation()}],1);assert.equal(next.units[0]!.shields[0]!.remaining,750);next=advanceBattle(next,100).battle;assert.equal(next.units[0]!.shields[0]!.remaining,750);next=advanceExplorationEffects(next,750);assert.equal(next.units[0]!.shields.length,0);assert.equal(next.units[0]!.speeds.length,0);assert.equal(next.units[0]!.actions['copy:b1:hit'],undefined);});
test('E24探索周期末新获得效果不扣除施加前的一秒',()=>{const a=grant('pulse',status('pulse',{scope:'run',duration:{clock:'permanent',value:0},tick:{clock:'exploration_time',interval:1000,count:1,action:'tick'}}));a.library!.actions.tick=action([{op:'explore',kind:'stealth',value:.5,duration:{clock:'exploration_time',value:1000}}]);let b=self(initial(),a);b=advanceExplorationEffects(b,1000);assert.equal(b.units[0]!.exploration![0]!.remaining,1000);b=advanceExplorationEffects(b,1000);assert.equal(b.units[0]!.exploration!.length,0);});

test('M07缺失种族不是全种族通配符，也不阻断已声明的技能',async()=>{const {HOST_RULES}=await import('../src/compiler/rules');let calls=0;const engine=createCompilationEngine(async()=>{calls++;return {};},HOST_RULES);for(const kind of [undefined,'','  ']){const source=cleanSource();source.种族=kind;const result=await engine.compile(source,undefined,[]);const actor=result.actor as import('../src/compiler/engine').CompiledActor;assert.equal(actor.skills.length,1);assert.equal(actor.skills[0]!.sourceId,'/技能/定量打击');}assert.equal(calls,3);});
test('E19/S05明确可奖励的敌方召唤物击败后计经验，召回与到期不算击败',()=>{const make=(rewardEligible:boolean,recall=false,count=1)=>{const s=startExpedition(playtestParty().slice(0,1),1),thing=s.region.things.find(t=>t.kind==='enemy')!;thing.foes=thing.foes.slice(0,1);s.mode='battle';s.encounterId=thing.id;s.run.battleActive=true;const p=s.party[0]!;s.battle=createBattle([{id:p.id,side:'ally',card:p.card,current:p.current,mitigation:bareMitigation()},{id:'enemy-0',side:'enemy',card:contentCard(1,100,10,{hit:hit(1)}),current:{hp:100,mp:65,sp:100},mitigation:bareMitigation()}],7);const summon=structuredClone(ABILITY_SAMPLES.familiar!);for(const tpl of Object.values(summon.library!.summons)){tpl.rewardEligible=rewardEligible;tpl.ownerDeath='persist';}if(summon.effects[0]!.op==='summon')summon.effects[0]!.count=count;s.battle=self(s.battle,summon,'enemy-0');const targets=s.battle.units.filter(u=>u.owner==='enemy-0');if(recall)s.battle=self(s.battle,action([{op:'recall',ownerOnly:true}]),'enemy-0');else for(const target of targets)s.battle=apply(s.battle,hit(10000),p.id,[target.id]);s.battle=act(s.battle,hit(10000),p.id,'enemy-0');requireTick(s,1);return s.run.participants[0]!.experience;};assert.equal(make(true),20);assert.equal(make(false),10);assert.equal(make(true,true),10);assert.equal(make(true,false,2),22);});
test('E21 延迟严格区分行动结束/行动开始与毫秒；下下次就绪才传送，恢复不重计',()=>{const delay=(clock:'target_action'|'target_ready',effects:EffectSpec[])=>{const a=action([{op:'time',mode:'delay',duration:{clock,value:2},action:'later',key:'two',restore:[]}]);a.library={...EMPTY_LIBRARY(),actions:{later:action(effects)}};return a;};let b=self(initial(),delay('target_action',[{op:'resource',resource:'sp',amount:flat(15),mode:'subtract'}]));b=advanceBattle(b,1000).battle;assert.equal(b.scheduled![0]!.remaining,2);b=act(b,action([{op:'atb',mode:'set',value:0}]),'a','a');assert.equal(b.units[0]!.current.sp,100);b=act(b,action([{op:'atb',mode:'set',value:0}]),'a','a');assert.equal(b.units[0]!.current.sp,85);
 const teleport=delay('target_ready',[{op:'retreat'}]);b=initial();b.units[0]!.library=structuredClone(teleport.library!);b=act(b,teleport,'a','a');b.clock.units[1]!.active=false;const nextReady=()=>{for(let i=0;i<30&&!b.clock.pending.length&&b.outcome==='active';i++)b=advanceBattle(b,1000).battle;};nextReady();assert.equal(b.scheduled![0]!.remaining,1);assert.equal(b.units[0]!.escaped,undefined);b=JSON.parse(JSON.stringify(b));assert.equal(advanceBattle(b,9999).consumedMs,0);b=act(b,action([{op:'atb',mode:'set',value:0}]),'a','a');nextReady();assert.equal(b.units[0]!.retreatRequested,true);assert.equal(b.scheduled!.length,0);
});
test('E12/E23 控制免疫按标准control键跨来源生效，不伪造成全精神伤害免疫',()=>{let b=self(initial(),action([{op:'rule',rule:'immune_status',key:'fear',duration:{clock:'permanent',value:0},priority:1000000}]));b.clock.units[0]!.haste=2;const fear=grant('foreign-key',status('来自别的能力的恐惧',{tags:[],control:'fear'}));fear.target='enemy';b=apply(b,fear,'b1',['a']);assert.equal(b.units[0]!.statuses!.filter(s=>s.definition.control==='fear').length,0);b=apply(b,action([guaranteed(10,'mental')],'enemy'),'b1',['a']);assert.equal(b.units[0]!.current.hp,90);});
test('E21/S05 原能力传送是个人成功脱离；不发当前战斗奖励、不重新入场，后续全败清此前账本',()=>{const s=startExpedition(playtestParty(),1),t=s.region.things.find(t=>t.kind==='enemy')!;t.foes=t.foes.slice(0,1);s.encounterId=t.id;s.mode='battle';s.run.battleActive=true;s.run.participants[0]!.experience=20;s.battle=createBattle([...s.party.map(p=>({id:p.id,side:'ally' as const,card:p.card,current:p.current,mitigation:bareMitigation()})),{id:'enemy-0',side:'enemy',card:contentCard(1,100,10,{hit:hit(1)}),current:{hp:100,mp:65,sp:100},mitigation:bareMitigation()}],7);const leave=action([{op:'retreat'}]);leave.cost.sp.flat=7;s.battle=act(s.battle,leave,'reader','reader');requireTick(s,1);assert.equal(s.run.participants[0]!.status,'voluntaryExit');assert.equal(s.run.participants[0]!.experience,20);assert.equal(s.run.participants[1]!.status,'active');assert.equal(s.run.battleActive,true);assert.equal(t.used,false);assert.equal(s.fights,0);assert.equal(s.party[0]!.current.sp,s.party[0]!.card.numeric.max.sp);s.battle=act(s.battle!,hit(10000),'enemy-0','keeper');requireTick(s,1);assert.equal(s.run.status,'failed');assert.equal(s.run.participants[0]!.experience,0);assert.equal(s.run.failureSignal!.finalDowned.length,1);});
test('E21/S05 原能力战外立即回归与战内延迟分支；不把空间位移伪造成退场',()=>{const ability=action([{op:'time',mode:'delay',duration:{clock:'target_ready',value:2},action:'return',key:'r',restore:[],conditions:[{kind:'phase',key:'battle'}]},{op:'retreat',conditions:[{kind:'phase',key:'exploration'}]}]);ability.library={...EMPTY_LIBRARY(),actions:{return:action([{op:'retreat'}])}};const party=playtestParty().slice(0,1);party[0]!.card=contentCard(3,150,16,{return:ability});const s=startExpedition(party,1);useOutsideBattle(s,'reader','return',['reader']);assert.equal(s.run.status,'success');assert.equal(s.mode,'ended');assert.equal(s.run.failureSignal,null);assert.equal(s.run.participants[0]!.status,'voluntaryExit');assert.equal(s.run.participants[0]!.experience,0);});

test('M09等待原生生成完成；无正文只记失败，显式补写一次，已生成正文不重复',async()=>{const {requestNarrativeOnce}=await import('../src/host/narrative');let vars:any={booksea:{}},calls=0,id=1,role='user';const h={getVariables:()=>vars,getLastMessageId:()=>id,getChatMessages:()=>[{role,message:'正文'}],updateVariablesWith:async(fn:any)=>{vars=fn(vars);},triggerSlash:async(cmd:string)=>{assert.equal(cmd,'/trigger await=true');calls++;if(calls===2){id++;role='assistant';}}},context={onlineStatus:'connected',saveChat:async()=>{}};await assert.rejects(requestNarrativeOnce(h,context,'exit:failed'),/未生成正文/);assert.equal(calls,1);assert.equal(vars.booksea.narrativeRequests['exit:failed'],'failed');await requestNarrativeOnce(h,context,'exit:failed');assert.equal(vars.booksea.narrativeRequests['exit:failed'],'delivered');await requestNarrativeOnce(h,context,'exit:failed');assert.equal(calls,2);});
