import test from 'node:test';
import assert from 'node:assert/strict';
import {validateAction,EMPTY_LIBRARY,MAX_ATTACK_BEATS,ROUND_MS,EFFECT_VERSION,type ActionSpec,type EffectSpec,type StatusSpec} from '../src/compiler/contract';
import {createBattle,applyBattleEffects,advanceBattle,chooseAction,resolveAction,actionUnavailable,type Battle} from '../src/battle/executor';
import {createCompilationEngine,CompilationBlocked} from '../src/compiler/engine';
import {Formula,type FormulaSpec} from '../src/compiler/formula';
import {card,flat,zero,mitigation,cleanSource,rules,mapping} from './compiler-fixtures';
const C=(n:number):FormulaSpec=>[{constant:n}];
const R=(read:'event'|'counter'|'counter_pair'|'variable'|'attribute'|'status_kinds',key:string,subject:'caster'|'target'='caster'):FormulaSpec=>[{read,key,subject}];
const expression=(x:FormulaSpec)=>({...flat(0),expression:x});
const action=(effects:EffectSpec[],target:ActionSpec['target']='enemy'):ActionSpec=>({target,cost:{hp:{flat:0,maxFraction:0},mp:{flat:0,maxFraction:0},sp:{flat:0,maxFraction:0}},castMs:0,recoveryFactor:1,perBattleUses:0,effects});
const hit=(n:number):Extract<EffectSpec,{op:'damage'}>=>({op:'damage',amounts:{physical:flat(n),energy:zero(),mental:zero(),true:zero()},element:'none',hitChance:1,hitRule:'guaranteed',critChance:0,critMultiplier:1});
const status=(name:string,extra:Partial<StatusSpec>={}):StatusSpec=>({name,tags:[name],polarity:'positive',duration:{clock:'permanent',value:0},stack:'refresh',maxStacks:24,scaleWithStacks:true,priority:0,dispellable:true,removeOnDeath:false,scope:'battle',...extra});
function initial(n=2,hp=500,allies=1):Battle{return createBattle(Array.from({length:n},(_,i)=>{const c=card();c.numeric.max.hp=hp;return {id:'u'+i,side:i<allies?'ally' as const:'enemy' as const,card:c,current:{hp,mp:80,sp:100},mitigation:mitigation()};}),7);}
const apply=(b:Battle,a:ActionSpec,caster='u0',targets=['u1'],key='test')=>applyBattleEffects(b,caster,validateAction(a),targets,'effect',key);
function grant(b:Battle,d:StatusSpec,owner='u1',actions:Record<string,ActionSpec>={}){const a=action([{op:'apply_status',status:d.name}],'self');a.library={...EMPTY_LIBRARY(),statuses:{[d.name]:d},actions};return apply(b,a,owner,[owner],d.name);}
function act(b:Battle,a:ActionSpec,caster='u0',target='u1',id='spell'){b=structuredClone(b);b.units.find(u=>u.id===caster)!.actions[id]=validateAction(a);b.clock.units.find(u=>u.id===caster)!.atb=100;b.clock.pending=[{kind:'ready',unitId:caster}];return resolveAction(chooseAction(b,caster,id,target));}
function idle(b:Battle,ms:number){b=structuredClone(b);b.clock.pending=[];for(const u of b.clock.units)u.active=false;return advanceBattle(b,ms).battle;}

test('段数：最多24，嵌套循环也不能拼出一万段',()=>{assert.equal(MAX_ATTACK_BEATS,24);assert.throws(()=>validateAction(action([{...hit(1),hits:25}])),/合同/);const a=action([{op:'sequence',action:'burst',repeat:4}]);a.library={...EMPTY_LIBRARY(),actions:{burst:action([{...hit(1),hits:7}])}};assert.throws(()=>validateAction(a),/24段/);const b=apply(initial(2,10000),action([{...hit(1),hits:24}]));assert.equal(b.units[1]!.current.hp,9976);});
test('表达式与分支图：拒绝坏栈、未知操作和同步递归',()=>{assert.throws(()=>Formula.parse([{operator:'add'}]));assert.throws(()=>Formula.parse([{constant:1},{constant:2}]));assert.throws(()=>Formula.parse([{read:'javascript',key:'eval'}]));const a=action([{op:'branch',when:[{kind:'resource',key:'hp'}],then:'loop'}]);a.library={...EMPTY_LIBRARY(),actions:{loop:action([{op:'repeat',action:'loop',count:C(1),limit:1}])}};assert.throws(()=>validateAction(a),/循环/);});

test('刁钻01 赌博毒针：一次抽3~8段，每段真叠毒，命中至少5次才转盾；同种子重放一致',()=>{
 const a=action([{op:'variable',key:'roll',mode:'random_int',value:C(3),maximum:C(8),targeting:{side:'self',selection:'manual'}},{...hit(3),hitCountExpression:R('variable','roll'),maxHits:8,onHitAction:'poison'},{op:'branch',targeting:{side:'self',selection:'manual'},when:[{kind:'expression',expression:R('event','hits'),value:5}],then:'shield',otherwise:'nothing'}]);
 a.library={...EMPTY_LIBRARY(),statuses:{venom:status('venom',{polarity:'negative',stack:'stack',duration:{clock:'round',value:2}})},actions:{poison:action([{op:'apply_status',status:'venom'}]),shield:action([{op:'shield',amount:expression([...R('event','hits'),{constant:2},{operator:'mul'}]),channels:['physical'],duration:{clock:'round',value:1}}],'self'),nothing:action([{op:'counter',key:'unlucky',mode:'add',value:C(1),reset:'battle'}],'self')}};
 const before=initial(),b=apply(before,a),count=b.units[1]!.statuses![0]!.stacks;assert.ok(count>=3&&count<=8);assert.equal(b.units[1]!.current.hp,500-count*3);assert.equal(b.units[0]!.shields[0]?.amount??0,count>=5?count*2:0);assert.deepEqual(b,apply(before,a));
});
test('刁钻02 伤痛账本：把实际扣血存进计数器，随后按账本结算，而非按原始攻击面板',()=>{
 let b=grant(initial(),status('ledger',{triggers:[{id:'save',event:'damage_received',scope:'self',action:'save'}]}),'u1',{save:action([{op:'counter',key:'pain',mode:'add',value:R('event','actual'),reset:'battle'}],'self')});
 b=apply(b,action([{...hit(17),hits:2}]));assert.equal(b.units[1]!.counters!.pain!.value,34);
 b=apply(b,action([{op:'heal',resource:'hp',amount:expression(R('counter','pain'))}],'self'),'u1',['u1']);assert.equal(b.units[1]!.current.hp,500);
});
test('刁钻03 复合检定：力量+敏捷对抗精神×2，成功附封印，失败走另一个动作',()=>{
 const a=action([{op:'check',attacker:[...R('attribute','力量'),...R('attribute','敏捷'),{operator:'add'}],defender:[...R('attribute','精神','target'),{constant:2},{operator:'mul'}],scale:1,baseChance:.5,minimumChance:0,maximumChance:1,success:'seal',failure:'miss'}]);a.library={...EMPTY_LIBRARY(),actions:{seal:action([{op:'uses',mode:'seal',skill:'*',value:1,duration:{clock:'round',value:1}}]),miss:action([{op:'counter',key:'failed',mode:'add',value:C(1),reset:'battle'}],'self')}};
 // 0.21：封印全部技能是强控，对同级可当场抵抗；这里只验证复合检定分支，施放者高1级（必定生效）。
 let b=initial();b.units[0]!.level+=1;b.units[0]!.attributes.力量=100;b=apply(b,a);assert.ok(Object.keys(b.units[1]!.sealed!).length>0);
 b=initial();b.units[0]!.attributes.力量=-100;b=apply(b,a);assert.equal(b.units[0]!.counters!.failed!.value,1);
});
test('刁钻04 有限命运：只保证下一次检定，不是假称整场绝对胜利',()=>{
 let b=apply(initial(),action([{op:'rule',rule:'luck',key:'best',uses:1,duration:{clock:'permanent',value:0}}],'self'),'u0',['u0']);const a=action([{op:'check',attacker:C(0),defender:C(100),scale:1,baseChance:0,minimumChance:0,maximumChance:0,success:'win',failure:'lose'}]);a.library={...EMPTY_LIBRARY(),actions:{win:action([hit(7)]),lose:action([{op:'counter',key:'loss',mode:'add',value:C(1),reset:'battle'}],'self')}};b=apply(b,a);assert.equal(b.units[1]!.current.hp,493);b=apply(b,a);assert.equal(b.units[1]!.current.hp,493);assert.equal(b.units[0]!.counters!.loss!.value,1);
});
test('刁钻05 枯荣领域：伤害变恢复、治疗变伤害，转换不会来回递归',()=>{
 const a=action([{op:'field',field:'reverse'}],'self');a.library={...EMPTY_LIBRARY(),fields:{reverse:{name:'reverse',group:'reality',priority:50,stack:'replace',targeting:{side:'any',selection:'all',life:'alive'},status:'law',duration:{clock:'round',value:2}}},statuses:{law:status('law',{triggers:[{id:'d',event:'before_damage',scope:'self',action:'d'},{id:'h',event:'before_heal',scope:'self',action:'h'}]})},actions:{d:action([{op:'alter_event',mode:'damage_to_heal'}],'self'),h:action([{op:'alter_event',mode:'heal_to_damage'}],'self')}};
 let b=initial();b.units[1]!.current.hp=200;b=apply(b,a,'u0',['u0']);b=apply(b,action([hit(30)]));assert.equal(b.units[1]!.current.hp,230);b=apply(b,action([{op:'heal',resource:'hp',amount:flat(20)}]));assert.equal(b.units[1]!.current.hp,210);assert.ok(b.log.length<40);
});
test('刁钻06 魔力税：对方已付20MP归我，已提交的瞬发伤害仍被取消',()=>{
 const intercept=action([{op:'heal',resource:'mp',amount:expression(R('event','paid_mp'))},{op:'alter_event',mode:'cancel_action'}],'self');let b=grant(initial(),status('tax',{triggers:[{id:'tax',event:'after_cost',scope:'enemy',action:'tax',conditions:[{kind:'expression',expression:R('event','paid_mp'),value:1}]}]}),'u1',{tax:intercept});b.units[1]!.level=2;/* 常驻必定无效只对低等级行动者生效 */b.units[1]!.current.mp=0;const spell=action([hit(70)]);spell.cost.mp.flat=20;b=act(b,spell);assert.equal(b.units[0]!.current.mp,60);assert.equal(b.units[1]!.current.mp,20);assert.equal(b.units[1]!.current.hp,500);
});
test('刁钻07 三人合唱：联合支付全部成功才扣款，缺成员/一人不足都不偷扣其他人',()=>{
 const a=action([hit(60)]);a.jointCost={targeting:{side:'ally',selection:'all',ids:['u0','u1','u2']},minimumParticipants:3,insufficient:'reject',cost:{hp:{flat:0,maxFraction:0},mp:{flat:20,maxFraction:0},sp:{flat:0,maxFraction:.1}}};let b=act(initial(4,500,3),a,'u0','u3');assert.deepEqual(b.units.slice(0,3).map(u=>[u.current.mp,u.current.sp]),[[60,90],[60,90],[60,90]]);assert.equal(b.units[3]!.current.hp,440);
 b=initial(4,500,3);b.units[2]!.current.mp=1;const before=structuredClone(b);assert.throws(()=>act(b,a,'u0','u3'),/资源不足/);assert.deepEqual(b,before);assert.throws(()=>act(initial(),a),/成员不足/);
});
test('多人各尽其余是显式支付策略，不是资源不足时隐式放行',()=>{const a=action([hit(1)]);a.jointCost={targeting:{side:'ally',selection:'all'},minimumParticipants:2,insufficient:'pay_remaining',cost:{hp:{flat:0,maxFraction:0},mp:{flat:30,maxFraction:0},sp:{flat:0,maxFraction:0}}};let b=initial(3,500,2);b.units[1]!.current.mp=5;b=act(b,a,'u0','u2');assert.deepEqual(b.units.slice(0,2).map(u=>u.current.mp),[50,0]);});
test('刁钻08 每个目标只斩一次：不是把整招限制为每战一次',()=>{const a=action([hit(9)]);a.perTargetUses=1;let b=act(initial(3),a,'u0','u1','scar');assert.match(actionUnavailable(b,b.units[0]!,'scar',['u1']),/该目标/);assert.equal(actionUnavailable(b,b.units[0]!,'scar',['u2']),'');b=act(b,a,'u0','u2','scar');assert.equal(b.units[1]!.current.hp,491);assert.equal(b.units[2]!.current.hp,491);});
test('刁钻09 命运交换：负面状态交换保留层数、剩余时长、周期动作与原来源',()=>{
 const a=action([{op:'apply_status',status:'poison',stacks:3}],'self');a.library={...EMPTY_LIBRARY(),statuses:{poison:status('poison',{polarity:'negative',stack:'stack',duration:{clock:'battle_time',value:5000},tick:{clock:'battle_time',interval:1000,count:0,action:'tick'}})},actions:{tick:action([hit(2)])}};
 let b=apply(initial(),a,'u0',['u0']);b=advanceBattle(b,250).battle;const st=b.units[0]!.statuses![0]!;const remaining=st.remaining,tickLeft=st.tickLeft;b=apply(b,action([{op:'status_transform',mode:'swap',polarity:'negative'}]));assert.equal(b.units[0]!.statuses!.length,0);assert.equal(b.units[1]!.statuses![0]!.remaining,remaining);assert.equal(b.units[1]!.statuses![0]!.tickLeft,tickLeft);assert.equal(b.units[1]!.statuses![0]!.stacks,3);b=advanceBattle(b,750).battle;assert.equal(b.units[1]!.current.hp,494);
});
test('刁钻10 负数祝福：减速与易伤数值倒转；不会猜测精神控制的反义词',()=>{let b=grant(initial(),status('weak',{polarity:'negative',modifiers:[{stat:'speed',multiplier:.5},{stat:'vulnerability',multiplier:2}]}));b=apply(b,action([{op:'status_transform',mode:'invert_numeric',polarity:'negative'}]));assert.equal(b.units[1]!.stats!.speed,2);assert.equal(b.units[1]!.stats!.vulnerability,.5);b=grant(b,status('fear',{polarity:'negative',control:'fear'}));b=apply(b,action([{op:'status_transform',mode:'invert_numeric',polarity:'negative'}]));assert.ok(b.log.some(x=>x.kind==='not_invertible'),'非数值状态未声明逆模板应明确记录');});
test('刁钻11 禁兵领域：真正停用装备被动数值和授予动作，法则来源保留，解封恢复',()=>{
 const c=card(),equip=action([{op:'damage_bonus',channel:'physical',flat:20,multiplier:1}],'self');equip.grantedActions=['slash'];equip.library={...EMPTY_LIBRARY(),actions:{slash:{...action([hit(4)]),name:'sword'}}};const law=action([{op:'modify',name:'law',duration:{clock:'permanent',value:0},modifiers:[{stat:'力量',flat:20}]}],'self');law.source={id:'law',kind:'law',priority:100};
 for(const [id,a] of [['/装备/剑',equip],['/登神长阶/法则',law]] as const)c.skills.push({sourceId:id,name:id,sourceFingerprint:'{}',mapping:{...mapping(a),sourceId:id,disposition:'passive'}});
 let b=createBattle([{id:'u0',side:'ally',card:c,current:{hp:100,mp:80,sp:100},mitigation:mitigation()},{id:'u1',side:'enemy',card:card(),current:{hp:100,mp:80,sp:100},mitigation:mitigation()}],7);const sword=Object.keys(b.units[0]!.actions).find(k=>k.endsWith('::slash'))!;assert.equal(b.units[0]!.damageBonus!.physical!.flat,20);
 const suppress=action([{op:'source',mode:'suppress',kinds:['equipment'],selection:'all',duration:{clock:'round',value:2},priority:50}]);b=apply(b,suppress,'u1',['u0']);assert.equal(b.units[0]!.damageBonus!.physical,undefined);assert.equal(b.units[0]!.attributes.力量,30);assert.match(actionUnavailable(b,b.units[0]!,sword,['u1']),/来源/);
 b=apply(b,action([{op:'source',mode:'restore',kinds:['equipment'],selection:'all',duration:{clock:'permanent',value:0},priority:50}]),'u1',['u0']);assert.equal(b.units[0]!.damageBonus!.physical!.flat,20);assert.equal(actionUnavailable(b,b.units[0]!,sword,['u1']),'');
});
test('刁钻12 记住你用过的招：只复制最近真正结算过的许可技能',()=>{let b=initial();const fire={...action([hit(8)]),name:'Gale',copyable:true};b=act(b,fire,'u1','u0','gale');b=apply(b,action([{op:'copy',mode:'skill',id:'*',selection:'used_latest',duration:{clock:'round',value:2}}]));const keys=Object.keys(b.units[0]!.actions).filter(k=>k.startsWith('copy:'));assert.deepEqual(keys,['copy:u1:gale']);assert.equal(b.units[0]!.actions[keys[0]!]!.name,'Gale');});
test('刁钻13 诅咒回邮：新负面状态原样送回施加者，不是反弹一个伤害数字',()=>{
 let b=grant(initial(),status('mail',{triggers:[{id:'return',event:'before_status',scope:'self',action:'return',conditions:[{kind:'expression',expression:R('event','status_negative'),value:1}]}]}),'u1',{return:action([{op:'alter_event',mode:'redirect',recipient:'event_source'}],'self')});const a=action([{op:'apply_status',status:'curse',stacks:2}]);a.library={...EMPTY_LIBRARY(),statuses:{curse:status('curse',{polarity:'negative',stack:'stack',duration:{clock:'round',value:3},modifiers:[{stat:'力量',flat:-2}]})}};b=apply(b,a);assert.equal(b.units[0]!.statuses!.find(s=>s.definition.name==='curse')!.stacks,2);assert.equal(b.units[1]!.statuses!.some(s=>s.definition.name==='curse'),false);
});
test('刁钻14 每公共轮最多失去33%最大HP：累计预算，而非简单减伤',()=>{let b=grant(initial(2,1000),status('cap',{reactions:[{kind:'damage_cap',amount:{...flat(0),subject:'target',maxResource:'hp',maxFraction:.33},reset:'round'}]}));b=apply(b,action([{...hit(400),hits:3}]));assert.equal(b.units[1]!.current.hp,670);b=idle(b,ROUND_MS);b=apply(b,action([hit(400)]));assert.equal(b.units[1]!.current.hp,340);});
test('刁钻15 魔力生命：1MP替代2HP损失，MP真耗尽后才掉血',()=>{let b=grant(initial(),status('mana-life',{reactions:[{kind:'resource_guard',resource:'mp',fraction:2}]}));b.units[1]!.current.mp=30;b=apply(b,action([hit(100)]));assert.equal(b.units[1]!.current.mp,0);assert.equal(b.units[1]!.current.hp,460);});
test('招架取消逐段附效与尾随附效；明确独立效果不被误取消',()=>{let b=grant(initial(),status('parry',{reactions:[{kind:'parry',fraction:1,chance:1}]}));const a=action([hit(40),{op:'apply_status',status:'curse'},{op:'counter',key:'independent',mode:'add',value:C(1),reset:'battle',independent:true}]);a.library={...EMPTY_LIBRARY(),statuses:{curse:status('curse',{polarity:'negative'})}};b=apply(b,a);assert.equal(b.units[1]!.current.hp,500);assert.equal(b.units[1]!.statuses!.some(s=>s.definition.name==='curse'),false);assert.equal(b.units[1]!.counters!.independent!.value,1);});
test('处决与复活按统一仲裁；施加者可用自身明确定义的解封通道',()=>{const revive=action([{op:'revive',amount:flat(50)}],'self');revive.targeting={side:'self',selection:'manual',life:'downed'};let b=grant(initial(),status('return',{triggers:[{id:'r',event:'after_down',scope:'self',action:'r'}]}),'u1',{r:revive});b.units[0]!.level=2;/* 处决只对低等级目标生效 */b=apply(b,action([{...hit(1000),execute:true,priority:1000}]));assert.equal(b.units[1]!.current.hp,0);assert.ok(b.log.some(x=>x.kind==='revive_blocked'));b=apply(b,{...action([{op:'revive',amount:flat(50),priority:1001}]),targeting:{side:'enemy',selection:'manual',life:'downed'}});assert.equal(b.units[1]!.current.hp,50);});
test('公共轮时钟：硬控到期不依赖被冻结者自己取得行动权',()=>{let b=grant(initial(),status('stun',{control:'stun',polarity:'negative',duration:{clock:'round',value:1}}));b=idle(b,ROUND_MS);assert.equal(b.units[1]!.statuses!.some(s=>s.definition.control==='stun'),false);assert.equal(b.clock.units[1]!.stopped,false);});
test('公共轮复活：死者无ATB仍能延迟复活；等待菜单时不偷走时钟',()=>{const revive=action([{op:'revive',amount:flat(50)}],'self');revive.targeting={side:'self',selection:'manual',life:'downed'};const a=action([{op:'time',mode:'delay',key:'return',action:'return',duration:{clock:'round',value:1},restore:[]}],'self');a.library={...EMPTY_LIBRARY(),actions:{return:revive}};let b=apply(initial(),a,'u0',['u0']);b=apply(b,action([hit(900)]),'u1',['u0']);b=idle(b,ROUND_MS);assert.equal(b.units[0]!.current.hp,50);const paused=structuredClone(b);paused.clock.paused=true;assert.equal(advanceBattle(paused,ROUND_MS).consumedMs,0);});
test('刁钻16 引导光束：每秒支付10MP才发出一轮，第三秒不足自动终止',()=>{const a=action([{op:'apply_status',status:'channel'}],'self');const pulse=action([{...hit(7),targeting:{side:'enemy',selection:'all'}}]);pulse.cost.mp.flat=10;a.library={...EMPTY_LIBRARY(),statuses:{channel:status('channel',{breakOnDamage:true,tick:{clock:'battle_time',interval:1000,action:'pulse',count:0,payCost:true}})},actions:{pulse}};let b=initial();b.units[0]!.current.mp=25;b=apply(b,a,'u0',['u0']);b=advanceBattle(b,3000).battle;assert.equal(b.units[0]!.current.mp,5);assert.equal(b.units[1]!.current.hp,486);assert.equal(b.units[0]!.statuses!.length,0);assert.ok(b.log.some(x=>x.kind==='channel_stopped'));});
test('刁钻17 延时签：提前抽定数字并存档，下一轮用原数字结算、不重抽',()=>{const a=action([{op:'variable',key:'ticket',mode:'random_int',value:C(7),maximum:C(7)},{op:'time',mode:'delay',action:'later',key:'ticket',duration:{clock:'round',value:1},restore:[]}],'self');a.library={...EMPTY_LIBRARY(),actions:{later:action([{op:'heal',resource:'hp',amount:expression(R('variable','ticket'))}],'self')}};let b=initial();b.units[0]!.current.hp=300;b=apply(b,a,'u0',['u0']);const restored=JSON.parse(JSON.stringify(b));const out=idle(restored,ROUND_MS);assert.equal(out.units[0]!.current.hp,307);assert.deepEqual(out,idle(b,ROUND_MS));});
test('对象选择：最低资源比例与排除标签，不把选择条件简化为随机',()=>{let b=initial(3,500,2);b.units[0]!.current.hp=100;b.units[1]!.current.hp=300;b=apply(b,action([{op:'heal',resource:'hp',amount:flat(20),targeting:{side:'ally',selection:'lowest_resource',resource:'hp',count:1}}],'ally'),'u0',['u1']);assert.equal(b.units[0]!.current.hp,120);assert.equal(b.units[1]!.current.hp,300);});
test('编译对照异常只重建说明，不丢弃已经可执行的动作',async()=>{
 const source=cleanSource(),missing=mapping();delete missing.fidelity;
 const first=await createCompilationEngine(async()=>({version:EFFECT_VERSION,mappings:[missing]}),rules).compile(source,undefined,[]);
 const c=first.actor as import('../src/compiler/engine').CompiledActor;assert.ok(c.skills[0]!.mapping.fidelity);assert.equal(c.skills[0]!.adaptation?.mode,'approximate');validateAction(c.skills[0]!.mapping.action);
 const approximate=mapping();approximate.fidelity!.mode='approximate';approximate.fidelity!.changes=[];
 const second=await createCompilationEngine(async()=>({version:EFFECT_VERSION,mappings:[approximate]}),rules).compile(source,undefined,[]);assert.ok((second.actor as import('../src/compiler/engine').CompiledActor).skills[0]!.mapping.fidelity!.changes.length);
});


test('嵌套伤害汇总不丢失：三次5伤害后产生7.5护盾',()=>{const a=action([{op:'sequence',action:'strike',repeat:3},{op:'shield',amount:{...flat(0),eventFraction:.5},channels:['physical'],duration:{clock:'round',value:1},targeting:{side:'self',selection:'manual'}}]);a.library={...EMPTY_LIBRARY(),actions:{strike:action([hit(5)])}};const b=apply(initial(),a);assert.equal(b.units[1]!.current.hp,485);assert.equal(b.units[0]!.shields[0]!.amount,7.5);});
test('双方反击不无限互打，反击自身的伤害汇总不污染原攻击',()=>{const retaliation=action([hit(10),{op:'shield',amount:{...flat(0),eventFraction:.5},channels:['energy'],duration:{clock:'round',value:1},targeting:{side:'self',selection:'manual'}}]);let b=grant(initial(),status('counter',{reactions:[{kind:'counter',action:'retaliate'}]}),'u1',{retaliate:retaliation});b=grant(b,status('counter',{reactions:[{kind:'counter',action:'retaliate'}]}),'u0',{retaliate:retaliation});b=apply(b,action([hit(20)]));assert.equal(b.log.filter(x=>x.kind==='damage').length,3);assert.equal(b.units[0]!.shields[0]!.amount,5);assert.equal(b.units[1]!.shields[0]!.amount,5);});
test('来源封锁也停用装备的速度、护盾和队伍光环；时间结束恢复原实例',()=>{
 const gear=action([{op:'speed',name:'gear-speed',multiplier:2,chance:1,duration:{clock:'permanent',value:0},stack:'refresh'},{op:'shield',amount:flat(50),channels:['physical'],duration:{clock:'permanent',value:0}},{op:'field',field:'aura'}],'self');gear.source={id:'gear',kind:'equipment'};gear.library={...EMPTY_LIBRARY(),statuses:{aura:status('aura',{modifiers:[{stat:'力量',flat:5}]})},fields:{aura:{name:'aura',group:'gear',priority:0,stack:'replace',targeting:{side:'ally',selection:'all'},status:'aura',duration:{clock:'permanent',value:0}}}};
 let b=apply(initial(3,500,2),gear,'u0',['u0']);assert.equal(b.clock.units[0]!.haste,2);assert.equal(b.units[1]!.attributes.力量,15);
 b=apply(b,action([{op:'speed',name:'封锁者加速',multiplier:3,chance:1,duration:{clock:'permanent',value:0},stack:'refresh'}],'self'),'u2',['u2']);b=apply(b,action([{op:'source',mode:'suppress',id:'gear',selection:'all',duration:{clock:'battle_time',value:1000}}]),'u2',['u0']);assert.equal(b.clock.units[0]!.haste,1);assert.equal(b.units[1]!.attributes.力量,10);assert.equal(b.units[0]!.shields[0]!.suppressed,true);
 b=apply(b,action([hit(20)]),'u2',['u0']);assert.equal(b.units[0]!.current.hp,480);assert.equal(b.units[0]!.shields[0]!.amount,50);b=idle(b,1000);assert.equal(b.clock.units[0]!.haste,2);assert.equal(b.units[1]!.attributes.力量,15);assert.equal(b.units[0]!.shields[0]!.suppressed,false);
});
test('缺陷字段不再能伪装合法编译：硬控自身时钟、假资源字段均拒绝',()=>{const a=action([{op:'apply_status',status:'trap'}]);a.library={...EMPTY_LIBRARY(),statuses:{trap:status('trap',{control:'stun',duration:{clock:'target_ready',value:1}})}};assert.throws(()=>validateAction(a),/冻结者/);assert.throws(()=>Formula.parse([{read:'event',key:'nonexistent_paid_magic'}]),/不存在/);assert.throws(()=>Formula.parse([{read:'resource',key:'mana'}]),/不存在/);});
test('有吟唱的扣费后取消也立即进入取消结算，不空等整个施法条',()=>{let b=grant(initial(),status('stop',{triggers:[{id:'s',event:'after_cost',scope:'enemy',action:'stop'}]}),'u1',{stop:action([{op:'alter_event',mode:'cancel_action'}],'self')});b.units[1]!.level=2;/* 常驻必定无效只对低等级行动者生效 */const a=action([hit(80)]);a.castMs=5000;a.cost.mp.flat=10;b=act(b,a);assert.equal(b.units[1]!.current.hp,500);assert.equal(b.clock.timeMs,0);assert.equal(b.units[0]!.current.mp,70);});
test('条件式延迟复活：等待分支实际执行，成功复苏，失败才全灭',()=>{for(const probability of [0,1]){const revive={...action([{op:'revive',amount:flat(50)}],'self'),targeting:{side:'self' as const,selection:'manual' as const,life:'downed' as const}},check=action([{op:'check',attacker:C(0),defender:C(0),scale:1,baseChance:probability,minimumChance:probability,maximumChance:probability,success:'revive'}],'self');check.targeting={side:'self',selection:'manual',life:'downed'};const a=action([{op:'time',mode:'delay',key:'return',action:'roll',duration:{clock:'round',value:1},restore:[]}],'self');a.library={...EMPTY_LIBRARY(),actions:{roll:check,revive}};let b=apply(initial(),a,'u0',['u0']);b=apply(b,action([hit(900)]),'u1',['u0']);b=idle(b,ROUND_MS);assert.equal(b.units[0]!.current.hp,probability?50:0);assert.equal(b.outcome,probability?'active':'defeat');}});
test('错误原文引用会被实际来源修正，但有效动作照常保存',async()=>{const source=cleanSource(),m=mapping();m.fidelity!.clauses[0]!.original='原文里不存在的绝对必胜';const result=await createCompilationEngine(async()=>({version:EFFECT_VERSION,mappings:[m]}),rules).compile(source,undefined,[]);const actor=result.actor as import('../src/compiler/engine').CompiledActor;assert.ok(!actor.skills[0]!.mapping.fidelity!.clauses.some(c=>c.original.includes('绝对必胜')));assert.match(actor.skills[0]!.sourceFingerprint,/10SP/);assert.doesNotMatch(result.notes.join('\n'),/sourceId|保真对照引用了/);validateAction(actor.skills[0]!.mapping.action);});

test('状态模板引用在条件/公式中与中文显示名不同，也必须真的匹配',()=>{const a=action([{op:'apply_status',status:'mark-id',stacks:3},{...hit(0),amounts:{physical:expression([{read:'status_stacks',subject:'target',key:'mark-id'},{constant:10},{operator:'mul'}]),energy:zero(),mental:zero(),true:zero()},conditions:[{kind:'status',subject:'target',key:'mark-id',value:3}]}]);a.library={...EMPTY_LIBRARY(),statuses:{'mark-id':status('显示名不同的烙印',{stack:'stack',polarity:'negative'})}};const b=apply(initial(),a);assert.equal(b.units[1]!.current.hp,470);});


test('编译教学样例均有真原文对照、合法动作图和可保存的编译结果（模型用mock）',async()=>{const {ADVANCED_EXAMPLES}=await import('../src/compiler/advanced-examples');for(const sample of ADVANCED_EXAMPLES){validateAction(sample.mapping.action);const source=cleanSource();source.技能={[sample.name]:{效果:sample.original}};const result=await createCompilationEngine(async()=>({version:EFFECT_VERSION,mappings:[sample.mapping]}),rules).compile(source,undefined,[]);assert.ok(result.actor);const actor=result.actor as import('../src/compiler/engine').CompiledActor;assert.ok(actor.skills[0]!.sourceFingerprint.includes(sample.original));validateAction(actor.skills[0]!.mapping.action);}});
test('现实反转示例明确只反转HP治疗，不偷换成连MP恢复都扣血',async()=>{const {ADVANCED_EXAMPLES}=await import('../src/compiler/advanced-examples');let b=initial();b.units[1]!.current.hp=200;b.units[1]!.current.mp=0;b=apply(b,ADVANCED_EXAMPLES[2]!.mapping.action,'u0',['u0']);b=apply(b,action([{op:'heal',resource:'mp',amount:flat(20)}]));assert.equal(b.units[1]!.current.mp,20);assert.equal(b.units[1]!.current.hp,200);b=apply(b,action([{op:'heal',resource:'hp',amount:flat(20)}]));assert.equal(b.units[1]!.current.hp,180);});
test('较低优先级事件改写不能覆盖更高优先级的伤转疗规则',()=>{let b=initial();b.units[1]!.current.hp=200;b=grant(b,status('high',{priority:100,triggers:[{id:'high',event:'before_damage',scope:'self',action:'high'}]}),'u1',{high:action([{op:'alter_event',mode:'damage_to_heal'}],'self')});b=grant(b,status('low',{priority:0,triggers:[{id:'low',event:'before_damage',scope:'self',action:'low'}]}),'u1',{low:action([{op:'alter_event',mode:'scale',value:C(0)}],'self')});b=apply(b,action([hit(30)]));assert.equal(b.units[1]!.current.hp,230);assert.ok(b.log.some(x=>x.kind==='rewrite_ignored'));});
