// Build-time extraction from the supplied host snapshot; never evaluate model-generated code.
import fs from 'node:fs';import ts from 'typescript';import {transformSync} from 'esbuild';import {createHash} from 'node:crypto';
const path='../05-外链源码快照-只读/【命定之诗】自动化脚本.js',source=fs.readFileSync(path,'utf8'),ast=ts.createSourceFile(path,source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);
const vars=new Map();for(const stmt of ast.statements)if(ts.isVariableStatement(stmt))for(const d of stmt.declarationList.declarations)vars.set(d.name.getText(ast),d.initializer?.getText(ast));
const wanted=['P','j','A','k','I','O','w','V','L','U','D','G','S','R','q','F','T','B','X','W','Y','H','J','K','Q','Z','tt','et','rt','at','st','nt','lt','it','ut','pt','ct','_t','dt'];
for(const n of wanted)if(!vars.has(n))throw Error('Host source binding missing: '+n);
const arrows=[];const walk=n=>{if(ts.isArrowFunction(n))arrows.push(n.getText(ast));ts.forEachChild(n,walk);};walk(ast);
const choose=fragment=>arrows.filter(s=>s.includes(fragment)).sort((a,b)=>a.length-b.length)[0];
let npc=choose('date.npcLevelUpWithPlayer'),player=choose('r.属性点') ;
// The player's arrow must contain the actual level-up loop, not the accessor.
player=arrows.filter(s=>s.includes('r.累计经验值>=Number(r.升级所需经验)')&&s.includes('属性点')).sort((a,b)=>a.length-b.length)[0];
const changes=[['if(!M(t,"date.npcLevelUpWithPlayer",!0))return;',''],['const z=!l&&!c','const z=!c'],['z&&u.在场&&o>0&&(!a||u.命定契约)&&u.等级<h&&_.set(s,"exp",s.exp+o);','']];
for(const [a,b] of changes){if(!npc.includes(a))throw Error('Host NPC adaptation point changed: '+a);npc=npc.replace(a,b);}
const hash=createHash('sha256').update(source).digest('hex');
const code=`// @ts-nocheck\n// GENERATED from host automation snapshot SHA256 ${hash}.\n// Only the NPC broadcast/initial-message gates are removed. Original thresholds, attributes, caps and growth loops are reused.\nexport const GROWTH_SOURCE_SHA256=${JSON.stringify(hash)};\nexport function sourceGrowth(_,work,before,messageId=10){\nconst M=_.get;const getLastMessageId=()=>messageId;const getVariables=()=>work;const toastr={warning:()=>{}};const insertOrAssignVariables=v=>_.merge(work,v);\n${wanted.map(n=>'const '+n+'='+vars.get(n)+';').join('\n')}\nconst player=${player};const npc=${npc};\nreturn {threshold:L,base:dt,player:()=>{lt(work,before);player(work,before);dt(work.stat_data.主角);},npcs:()=>{npc(work,before);for(const a of Object.values(work.stat_data.关系列表))dt(a);}};\n}\n`;
const output=transformSync(code,{loader:'ts',format:'esm',minify:false,charset:'utf8'}).code;
fs.writeFileSync('src/host/source-growth.ts','// @ts-nocheck\n// GENERATED by scripts/build-growth.mjs; source-derived host algorithm.\n'+output);
fs.mkdirSync('../17-宿主可玩联调/verification',{recursive:true});fs.writeFileSync('../17-宿主可玩联调/verification/growth-provenance.json',JSON.stringify({source:path,sha256:hash,adaptation:'Per-participant NPC experience, no player broadcast, no early-message gating; source growth math unchanged',bindings:wanted},null,2)+'\n');
console.log('Extracted original host growth algorithms for per-participant settlement.');
