import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {mimicKit,MIMIC_ID} from '../src/game/monsters/mimic';
import {TIER_START} from '../src/game/monsters/numbers';
import {MONSTER_ROSTER} from '../src/game/monsters/catalog';
import {validateCompiled} from '../src/compiler/engine';
import {describeAction} from '../src/ui/ability-text';
import {enemyArtId} from '../src/presentation/monster-art';
const root='../20-正式怪物美术/M3-交互点与宝箱怪/metadata';await mkdir(root,{recursive:true});
const ranges=['1–4（模板保留，实际不会在此等级生成）','5–8（实际最低6级）','9–12','13–16','17–20','21–24','25及以上'];
const kits=TIER_START.map((level,i)=>{const kit=mimicKit(level);validateCompiled(kit.card);return {...kit,levelRange:ranges[i],encounterLevelRule:'max(6, 当前层普通怪挑战等级+5)',spawnRate:.08,independentFromRealChests:true,normalEscape:false,explicitRetreatSkillsAllowed:true,defeatLoot:{kind:'box',count:1,guaranteed:true,unopened:true}};});
await writeFile(root+'/mimic-kits-7.json',JSON.stringify(kits,null,2)+'\n');
const quote=(v:unknown)=>'"'+String(v??'').replaceAll('"','""')+'"';
const rows=[['生命层级','参考等级','等级范围','普通技能','升阶能力','主动效果说明','被动效果说明','生成与结算规则'],...kits.map(k=>[k.numbers.lifeTier,k.numbers.displayLevel,k.levelRange,k.regular.join('；'),k.ascended.join('；'),k.card.skills.filter(s=>s.mapping.disposition==='active').map(s=>s.name+'：'+describeAction(s.mapping.action!,k.card.numeric).join('；')).join('\n'),k.card.skills.filter(s=>s.mapping.disposition==='passive').map(s=>s.name+'：'+describeAction(s.mapping.action!,k.card.numeric).join('；')).join('\n'),'每层独立8%；等级+5、最低6；禁止普通逃跑；专门离场技能可用；击败必得1个未开启盲盒'])];
await writeFile('../01-计划与制作清单/宝箱怪七生命层级技能模板.csv','\uFEFF'+rows.map(r=>r.map(quote).join(',')).join('\n')+'\n');
const manifest=JSON.parse(await readFile('../16-Godot可玩区域/godot/monsters/manifest.json','utf8'));const art=new Map(manifest.characters.map((x:any)=>[x.id,x]));
const bindings=MONSTER_ROSTER.filter(m=>m.id!==m.designId).map(m=>({runtimeId:m.id,name:m.name,artId:enemyArtId({id:'enemy-0'},[{id:'enemy-0'}],[m.id]),file:(art.get(m.designId) as any)?.battle?.file,sourceName:(art.get(m.designId) as any)?.name}));
if(bindings.some(b=>b.name!==b.sourceName||!b.file))throw Error('Art binding/name mismatch');
await writeFile(root+'/corrected-art-bindings-128.json',JSON.stringify(bindings,null,2)+'\n');
await writeFile('../01-计划与制作清单/怪物立绘绑定修复清单-024.csv','\uFEFF'+[['战斗ID','怪物名称','实际美术ID','图片文件','处理'],...bindings.map(b=>[b.runtimeId,b.name,b.artId,b.file,'按designId绑定；原图存在，无需补画'])].map(r=>r.map(quote).join(',')).join('\n')+'\n');
console.log(JSON.stringify({mimic:MIMIC_ID,templates:kits.length,correctedBindings:bindings.length,commonPortraits:1,originalThemePortraits:432}));
