import {EMPTY_LIBRARY,type ActionSpec,type EffectSpec,type LibrarySpec,type ConditionSpec} from './contract';
/** Bind a source's finite definition graph once. Unused catalog recipes and per-button duplicate libraries are not saved. */
export function bindLibrary(input:ActionSpec,prefix:string):ActionSpec{
 const a=structuredClone(input),source=a.library;if(!source)return a;
 const lib=EMPTY_LIBRARY(),seen=new Set<string>(),id=(key:string)=>prefix+'::'+key;
 function expressions(value:unknown){if(!value||typeof value!=='object')return;if(Array.isArray(value)){value.forEach(expressions);return;}const v=value as Record<string,unknown>;if(v.read==='status_stacks'&&typeof v.key==='string'&&source!.statuses[v.key]){const k=v.key;visit('statuses',k);v.key=id(k);}for(const x of Object.values(v))expressions(x);}
 function conditions(cs:ConditionSpec[]|undefined){expressions(cs);for(const c of cs??[])if(c.kind==='status'&&c.key&&source!.statuses[c.key]){visit('statuses',c.key);c.key=id(c.key);}else if(c.kind==='field'&&c.key&&source!.fields[c.key]){visit('fields',c.key);c.key=id(c.key);}}
 function effects(es:EffectSpec[]){for(const e of es){expressions(e);conditions(e.conditions);if(e.op==='choose')e.actions=e.actions.map(k=>{visit('actions',k);return id(k);});if(e.op==='rule'&&e.onTrigger){visit('actions',e.onTrigger);e.onTrigger=id(e.onTrigger);}if(e.op==='damage'&&e.onHitAction){visit('actions',e.onHitAction);e.onHitAction=id(e.onHitAction);}if(e.op==='branch'){conditions(e.when);for(const k of ['then','otherwise'] as const)if(e[k]){visit('actions',e[k]!);e[k]=id(e[k]!);}}if(e.op==='check')for(const k of ['success','failure'] as const)if(e[k]){visit('actions',e[k]!);e[k]=id(e[k]!);}if(e.op==='apply_status'){visit('statuses',e.status);e.status=id(e.status);}else if(e.op==='summon'){visit('summons',e.template);e.template=id(e.template);}else if(e.op==='field'){visit('fields',e.field);e.field=id(e.field);}else if(e.op==='sequence'||e.op==='repeat'||e.op==='time'&&e.action){visit('actions',e.action!);e.action=id(e.action!);}else if(e.op==='uses'&&source!.actions[e.skill]){visit('actions',e.skill);e.skill=id(e.skill);}}}
 function visit(group:keyof LibrarySpec,key:string){const mark=group+':'+key;if(seen.has(mark))return;seen.add(mark);
  if(group==='actions'){const d=structuredClone(source!.actions[key]!);d.name??=key;lib.actions[id(key)]=d;effects(d.effects);conditions(d.conditions);d.grantedActions=d.grantedActions?.map(k=>{visit('actions',k);return id(k);});if(!d.grantedActions)delete d.grantedActions;}
  if(group==='statuses'){const d=structuredClone(source!.statuses[key]!);lib.statuses[id(key)]=d;expressions(d);if(d.inverse){visit('statuses',d.inverse);d.inverse=id(d.inverse);}if(d.onExpire){visit('actions',d.onExpire);d.onExpire=id(d.onExpire);}if(d.tick){visit('actions',d.tick.action);d.tick.action=id(d.tick.action);}for(const t of d.triggers??[]){visit('actions',t.action);t.action=id(t.action);conditions(t.conditions);}for(const r of d.reactions??[])if(r.action){visit('actions',r.action);r.action=id(r.action);}}
  if(group==='summons'){const d=structuredClone(source!.summons[key]!);lib.summons[id(key)]=d;d.actions=d.actions.map(k=>{visit('actions',k);return id(k);});}
  if(group==='fields'){const d=structuredClone(source!.fields[key]!);lib.fields[id(key)]=d;visit('statuses',d.status);d.status=id(d.status);}
 }
 effects(a.effects);conditions(a.conditions);for(const t of a.triggers??[]){visit('actions',t.action);t.action=id(t.action);conditions(t.conditions);}if(a.grantedActions)a.grantedActions=a.grantedActions.map(k=>{visit('actions',k);return id(k);});a.library=lib;return a;
}
