// @ts-nocheck
// GENERATED by scripts/build-growth.mjs; source-derived host algorithm.
const GROWTH_SOURCE_SHA256 = "b09076ee0cbf0d84641d6e7a3b67a4238fcdf86e0ec33db045cf3d9379a9729e";
function sourceGrowth(_, work, before, messageId = 10) {
  const M = _.get;
  const getLastMessageId = () => messageId;
  const getVariables = () => work;
  const toastr = { warning: () => {
  } };
  const insertOrAssignVariables = (v) => _.merge(work, v);
  const P = { 5: { attributes: 1, tier: "第二层级/中坚" }, 9: { attributes: 1, tier: "第三层级/精英" }, 13: { attributes: 1, tier: "第四层级/史诗" }, 17: { attributes: 1, tier: "第五层级/传说" }, 21: { attributes: 1, tier: "第六层级/神话" }, 25: { attributes: 1, tier: "第七层级/登神" } };
  const j = { 0: 0, 1: 120, 2: 360, 3: 720, 4: 1200, 5: 2400, 6: 3840, 7: 5520, 8: 7440, 9: 11940, 10: 16940, 11: 22440, 12: 28440, 13: 38840, 14: 50040, 15: 62040, 16: 74840, 17: 100340, 18: 127340, 19: 155840, 20: 185840, 21: 236240, 22: 289040, 23: 344240, 24: 401840, 25: "MAX" };
  const A = 1;
  const k = 13;
  const I = 25;
  const O = ["力量", "敏捷", "体质", "智力", "精神"];
  const w = (t) => P[t];
  const V = (t) => {
    const e = _.chain(P).toPairs().map(([t2, e2]) => ({ level: Number(t2), data: e2 })).filter(({ level: e2 }) => t >= e2).value();
    return _.maxBy(e, "level")?.data.tier ?? "第一层级/普通";
  };
  const L = (t) => _.get(j, t, "MAX");
  const U = (t) => t >= I;
  const D = { 1: 1, 5: 2, 9: 4, 13: 10, 17: 20, 21: 40, 25: 100 };
  const G = { 1: 1, 5: 2.5, 9: 6, 13: 15, 17: 35, 21: 80, 25: 160 };
  const S = (t, e) => {
    const r = _.chain(t).keys().map(Number).filter((t2) => e >= t2).value(), a = _.max(r);
    return void 0 === a ? t[1] : t[a];
  };
  const R = [12, 16, 20, 24];
  const q = "登神·启明之阶";
  const F = "登神·铸权之仪";
  const T = "登神·定律誓约";
  const B = "登神·登神仪式";
  const X = "登神·神国初立";
  const W = { [q]: { "状态": "进行中", "关注度": "高", "进展": "尚未开始收集要素。", "详情": "等级已锁，无法获取经验，需满足条件：获取至少 1 个要素。", "目标": "以一枚要素点燃登神之火，让长阶回应你的名。", "奖励": "长阶初启，神火与要素共鸣。" }, [F]: { "状态": "进行中", "关注度": "高", "进展": "权能尚未开始融合。", "详情": "等级已锁，无法获取经验，需满足条件：融合 3 个要素为 1 个权能。", "目标": "三要素归一，淬炼成唯一权能。", "奖励": "权能成形，诸力归位于你。" }, [T]: { "状态": "进行中", "关注度": "高", "进展": "法则源质未准备就绪。", "详情": "等级已锁，无法获取经验，需满足条件：以权能融合法则源质，铸成法则。", "目标": "寻得法则源质，与权能相合，点燃法则真名。", "奖励": "法则凝就，秩序向你低首。" }, [B]: { "状态": "进行中", "关注度": "高", "进展": "登神仪式尚未筹备。", "详情": "等级已锁，无法获取经验，需满足条件：获得神位。", "目标": "行登神之礼，确立神位。", "奖励": "神位应诺，尊名刻入天穹。" }, [X]: { "状态": "进行中", "关注度": "高", "进展": "神国建设尚未启动。", "详情": "完成条件：建立神国。", "目标": "赐予神国之名，令其在诸界立足。", "奖励": "神国初立，法则之缚自此尽解。" } };
  const Y = /法则源质/;
  const H = /^༺.+༻$/;
  const J = (t) => _.filter(_.keys(t), (e) => ((t2, e2) => {
    if (!H.test(String(e2))) return false;
    const r = M(t2, "标签", []);
    return !!Array.isArray(r) && r.some((t3) => Y.test(String(t3)));
  })(M(t, e, {}), String(e)));
  const K = (t) => J(t).length > 0;
  const Q = (t) => {
    const e = ((t2) => {
      const e2 = Number(M(t2, "升级所需经验", 0));
      return Number.isFinite(e2) ? e2 : null;
    })(t);
    return null !== e && M(t, "累计经验值", 0) >= e;
  };
  const Z = (t, e) => {
    _.has(t, e) || _.set(t, e, W[e]);
  };
  const tt = (t, e) => {
    _.has(t, e) && _.unset(t, e);
  };
  const et = (t) => ({ elementCount: _.size(M(t, "要素", {})), powerCount: _.size(M(t, "权能", {})), lawCount: _.size(M(t, "法则", {})), hasGodPosition: !!M(t, "神位", ""), hasGodNationName: !!M(t, "神国.名称", "") });
  const rt = (t, e) => {
    if (!R.includes(t)) return true;
    const r = M(e, "stat_data.主角", {}), a = M(r, "登神长阶", {}), { elementCount: s, powerCount: n, lawCount: o, hasGodPosition: l } = et(a);
    switch (t) {
      case 12:
        return s > 0;
      case 16:
        return n > 0;
      case 20:
        return o > 0;
      case 24:
        return o > 0 && l;
      default:
        return true;
    }
  };
  const at = (t, e) => {
    const r = M(t, "stat_data.主角", {}), a = M(t, "stat_data.任务列表", {}), s = M(r, "登神长阶", {}), { elementCount: n, powerCount: o, lawCount: l, hasGodPosition: i, hasGodNationName: u } = et(s), p = Number(M(r, "等级", 1)), c = Q(r), d = M(r, "背包", {}), f = J(d), g = f.length > 0, m = M(e ?? {}, "stat_data.主角.登神长阶", {}), z = _.size(M(m, "法则", {})), h = M(e ?? {}, "stat_data.主角.背包", {}), b = K(h);
    20 === p && l > 0 && !g && !b && _.set(r, "登神长阶.法则", {});
    const y = p >= k || 12 === p && c;
    _.set(r, "登神长阶.是否开启", M(s, "是否开启", false) || y), 12 === p && c && 0 === n ? Z(a, q) : tt(a, q), 16 === p && c && 3 === n && 0 === o ? Z(a, F) : tt(a, F), 20 === p && c && o >= 1 && 0 === l ? Z(a, T) : tt(a, T), 24 === p && c && l >= 1 && !i ? Z(a, B) : tt(a, B), 25 === p && l >= 2 && !u ? Z(a, X) : tt(a, X), 0 === z && l > 0 && ((t2, e2) => {
      1 === e2.length && _.forEach(e2, (e3) => {
        _.unset(t2, e3);
      });
    })(d, f), _.set(t, "date.ascensionLawReady", K(d));
  };
  const st = { deathCount: 0, maxCurrencyDebt: 0, bankruptcyCount: 0, illegalLevelUpId: [], totalFPGained: 0, timeRecord: {}, locationRecord: {} };
  const nt = (t) => {
    const e = M(t, "date.log", null);
    return e || { ...st };
  };
  const lt = (t, e) => {
    const r = M(t, "stat_data.主角", {}), a = _.has(e, "stat_data.主角.等级"), s = M(e, "stat_data.主角.等级", 1), n = getLastMessageId() <= 2;
    if (at(t, e), !n && a && s < r.等级) {
      const t2 = Number(M(r, "升级所需经验", 0));
      Number.isFinite(t2) && Number(M(r, "累计经验值", 0)) >= t2 && r.等级 === s + 1 ? _.set(r, "等级", s) : (_.set(r, "等级", s), (() => {
        const t3 = getVariables({ type: "message" }), e2 = nt(t3), r2 = getLastMessageId();
        e2.illegalLevelUpId.includes(r2) || e2.illegalLevelUpId.push(r2), insertOrAssignVariables({ date: { log: { illegalLevelUpId: e2.illegalLevelUpId } } }, { type: "message" });
      })(), toastr.warning("等级被AI非法提升,请检查变量更新"));
    }
    if (_.set(r, "升级所需经验", L(r.等级)), r.等级 > 0) {
      const t2 = L(r.等级 - 1), a2 = Number(r.累计经验值) || 0, s2 = M(e, "stat_data.主角.累计经验值", a2), n2 = Math.max(a2, Number(t2) || 0, s2);
      r.累计经验值 !== n2 && _.set(r, "累计经验值", n2);
    }
    _.set(r, "生命层级", V(r.等级));
  };
  const it = { "第一层级/普通": 8, "第二层级/中坚": 10, "第三层级/精英": 12, "第四层级/史诗": 14, "第五层级/传说": 16, "第六层级/神话": 18, "第七层级/登神": 20 };
  const ut = (t) => it[t] ?? 8;
  const pt = /* @__PURE__ */ new Set([12, 16, 20, 24]);
  const ct = (t, e, r, a) => {
    const s = [];
    if (_.forEach(O, (n2) => {
      const o2 = Number(t[n2] || 0);
      if (o2 + Number(e[n2] || 0) + Number(r[n2] || 0) >= a) return;
      const l2 = Math.max(1, o2 * o2);
      s.push({ key: n2, weight: l2 });
    }), 0 === s.length) return null;
    const n = _.sumBy(s, "weight");
    let o = Math.random() * n, l = s[s.length - 1]?.key ?? O[0];
    for (const i of s) if (o -= i.weight, o <= 0) {
      l = i.key;
      break;
    }
    return l;
  };
  const _t = (t, e) => Number(M(t, `属性.${e}`, 0)) || 0;
  const dt = (t, e = false) => {
    const r = Number(M(t, "等级", 1)) || 1, a = ((t2) => S(D, t2))(r), s = ((t2) => S(G, t2))(r), n = _t(t, "力量"), o = _t(t, "敏捷"), l = _t(t, "体质"), i = _t(t, "智力"), u = _t(t, "精神"), p = n + o + l + i + u, c = Math.round(100 * l * a + p), d = Math.round(50 * (i + u) * s), f = Math.round(50 * (n + o) * s);
    _.set(t, "生命值.上限._基础", c), _.set(t, "法力值.上限._基础", d), _.set(t, "体力值.上限._基础", f);
    const g = Number(M(t, "生命值.当前", 0)) || 0, m = Number(M(t, "法力值.当前", 0)) || 0, z = Number(M(t, "体力值.当前", 0)) || 0, h = Math.max(0, c + Number(M(t, "生命值.上限.额外", 0))), b = Math.max(0, d + Number(M(t, "法力值.上限.额外", 0))), y = Math.max(0, f + Number(M(t, "体力值.上限.额外", 0)));
    _.set(t, "生命值.当前", e ? h : _.clamp(g, 0, h)), _.set(t, "法力值.当前", e ? b : _.clamp(m, 0, b)), _.set(t, "体力值.当前", e ? y : _.clamp(z, 0, y));
  };
  const player = (t, e) => {
    const r = M(t, "stat_data.主角", {}), a = M(e, "stat_data.主角.等级", r.等级), s = Number(r.属性点) || 0;
    let n = M(e, "stat_data.主角.生命层级", V(a));
    const o = _.fromPairs(_.map(O, (t2) => [t2, Number(M(r, `属性.${t2}`, 0)) || 0]));
    let l = 0;
    const i = [], u = _.fromPairs(_.map(O, (t2) => [t2, 0]));
    for (; r.累计经验值 >= Number(r.升级所需经验) && !U(r.等级); ) {
      if (!rt(r.等级, t)) {
        _.set(r, "累计经验值", Number(r.升级所需经验));
        break;
      }
      _.set(r, "等级", r.等级 + 1), _.set(r, "升级所需经验", L(r.等级)), r.等级 % A === 0 && (l += 1);
      const e2 = w(r.等级);
      e2 && (_.forEach(O, (t2) => {
        u[t2] += e2.attributes;
      }), _.set(r, "生命层级", e2.tier), n !== e2.tier && (i.push(`{{user}}的生命层级从${n}突破到了${e2.tier}`), n = e2.tier));
    }
    if (_.set(r, "属性点", s + l), _.forEach(O, (t2) => {
      _.set(r, `属性.${t2}`, o[t2] + u[t2]);
    }), _.set(r, "生命层级", V(r.等级)), r.等级 > a) {
      const t2 = [`{{user}}的等级从${a}级提升到了${r.等级}级`];
      l > 0 && t2.push(`{{user}}升级了，获得了${l}点属性点。引导{{user}}使用属性点`), i.length > 0 && t2.push(...i), insertOrAssignVariables({ date: { levelUpCharacter: t2 } }, { type: "message" });
    }
  };
  const npc = (t, e) => {
    const r = M(t, "stat_data.关系列表", {}), a = M(t, "date.requiresContractForExp", true);
    const s = M(t, "date.npcs", {}), n = M(t, "stat_data.主角.累计经验值", 0), o = n - M(e, "stat_data.主角.累计经验值", n), l = getLastMessageId() <= 3;
    _.forEach(r, (t2, e2) => {
      s[e2] || _.set(s, e2, { level: t2.等级, exp: 0, required_exp: L(t2.等级) });
    }), _.forEach(_.keys(s), (t2) => {
      r[t2] || _.unset(s, t2);
    });
    const i = [];
    _.forEach(s, (s2, n2) => {
      const u = r[n2];
      if (!u) return;
      const p = M(e, `stat_data.关系列表.${n2}.等级`, void 0), c = "number" != typeof p || p !== u.等级, d = _.fromPairs(_.map(O, (t2) => [t2, Number(M(u, `属性.${t2}`, 0)) || 0])), f = _.fromPairs(_.map(O, (t2) => [t2, 0])), g = _.fromPairs(_.map(O, (t2) => [t2, 0]));
      _.set(s2, "level", u.等级), _.set(s2, "required_exp", L(s2.level));
      const m = s2.level > 1 ? j[s2.level - 1] : 0;
      c ? "number" == typeof m && _.set(s2, "exp", m) : s2.level > 1 && "number" == typeof m && s2.exp < m && _.set(s2, "exp", m);
      const z = !c, h = M(t, "stat_data.主角.等级", 1);
      const b = u.等级;
      let y = M(e, `stat_data.关系列表.${n2}.生命层级`, V(b));
      for (; z && s2.exp >= s2.required_exp && !U(s2.level); ) {
        _.set(s2, "level", s2.level + 1), _.set(s2, "required_exp", L(s2.level));
        const t2 = V(s2.level), e2 = ut(t2);
        if (s2.level % A === 0) {
          const t3 = ct(d, f, g, e2);
          t3 && (f[t3] += 1);
        }
        const r2 = w(s2.level);
        r2 && _.forEach(O, (t3) => {
          g[t3] += r2.attributes;
        });
        const a2 = V(s2.level);
        if (y !== a2 && (i.push(`${n2}的生命层级从${y}突破到了${a2}`), y = a2), pt.has(s2.level)) break;
      }
      _.forEach(O, (t2) => {
        _.set(u, `属性.${t2}`, d[t2] + f[t2] + g[t2]);
      }), u.等级 < s2.level && (i.unshift(`${n2}从LV${b}提升到LV${s2.level}`), _.set(u, "等级", s2.level), _.set(u, "生命层级", V(s2.level)));
    }), i.length > 0 ? insertOrAssignVariables({ date: { npcs: s, levelUpNpcs: i } }, { type: "message" }) : insertOrAssignVariables({ date: { npcs: s } }, { type: "message" });
  };
  return { threshold: L, base: dt, player: () => {
    lt(work, before);
    player(work, before);
    dt(work.stat_data.主角);
  }, npcs: () => {
    npc(work, before);
    for (const a of Object.values(work.stat_data.关系列表)) dt(a);
  } };
}
export {
  GROWTH_SOURCE_SHA256,
  sourceGrowth
};
